//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MernisTc
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MernisTc.NkoSorgulaTCKimlikNoServisSoap")]
    public interface NkoSorgulaTCKimlikNoServisSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MernisTc.SorgulaResponse> SorgulaAsync(MernisTc.SorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SorgulaMP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MernisTc.NkoSonucu> SorgulaMPAsync(MernisTc.NkoTCKimlikNoSorguKriteri[] KriterList, string uName, string pwd, string sessionID, string SorgulayanKullanici);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader
    {
        
        private string usernameField;
        
        private string passwordField;
        
        private string sessionIDField;
        
        private string sorgulayanKullaniciField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SessionID
        {
            get
            {
                return this.sessionIDField;
            }
            set
            {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SorgulayanKullanici
        {
            get
            {
                return this.sorgulayanKullaniciField;
            }
            set
            {
                this.sorgulayanKullaniciField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KisiKayitYeriKodBilgisi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> aileSiraNoField;
        
        private System.Nullable<int> bireySiraNoField;
        
        private System.Nullable<int> ciltKodField;
        
        private System.Nullable<int> ilceKodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> AileSiraNo
        {
            get
            {
                return this.aileSiraNoField;
            }
            set
            {
                this.aileSiraNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> BireySiraNo
        {
            get
            {
                return this.bireySiraNoField;
            }
            set
            {
                this.bireySiraNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> CiltKod
        {
            get
            {
                return this.ciltKodField;
            }
            set
            {
                this.ciltKodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> IlceKod
        {
            get
            {
                return this.ilceKodField;
            }
            set
            {
                this.ilceKodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExtensionDataObject
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NkoOlay
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string adField;
        
        private string dusunceField;
        
        private Parametre hataBilgisiField;
        
        private KisiKayitYeriKodBilgisi kayitYeriField;
        
        private System.Nullable<long> olayKayitNoField;
        
        private TarihBilgisi olayTarihField;
        
        private Parametre olayTipiField;
        
        private string soyadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ad
        {
            get
            {
                return this.adField;
            }
            set
            {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Dusunce
        {
            get
            {
                return this.dusunceField;
            }
            set
            {
                this.dusunceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public KisiKayitYeriKodBilgisi KayitYeri
        {
            get
            {
                return this.kayitYeriField;
            }
            set
            {
                this.kayitYeriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<long> OlayKayitNo
        {
            get
            {
                return this.olayKayitNoField;
            }
            set
            {
                this.olayKayitNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public TarihBilgisi OlayTarih
        {
            get
            {
                return this.olayTarihField;
            }
            set
            {
                this.olayTarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Parametre OlayTipi
        {
            get
            {
                return this.olayTipiField;
            }
            set
            {
                this.olayTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Soyad
        {
            get
            {
                return this.soyadField;
            }
            set
            {
                this.soyadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Parametre
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string aciklamaField;
        
        private System.Nullable<int> kodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Aciklama
        {
            get
            {
                return this.aciklamaField;
            }
            set
            {
                this.aciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> Kod
        {
            get
            {
                return this.kodField;
            }
            set
            {
                this.kodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TarihBilgisi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> ayField;
        
        private System.Nullable<int> gunField;
        
        private System.Nullable<int> yilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> Ay
        {
            get
            {
                return this.ayField;
            }
            set
            {
                this.ayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> Gun
        {
            get
            {
                return this.gunField;
            }
            set
            {
                this.gunField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> Yil
        {
            get
            {
                return this.yilField;
            }
            set
            {
                this.yilField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KisiTemelBilgisi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string adField;
        
        private string anneAdField;
        
        private string babaAdField;
        
        private Parametre cinsiyetField;
        
        private TarihBilgisi dogumTarihField;
        
        private string dogumYerField;
        
        private string soyadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ad
        {
            get
            {
                return this.adField;
            }
            set
            {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AnneAd
        {
            get
            {
                return this.anneAdField;
            }
            set
            {
                this.anneAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BabaAd
        {
            get
            {
                return this.babaAdField;
            }
            set
            {
                this.babaAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Parametre Cinsiyet
        {
            get
            {
                return this.cinsiyetField;
            }
            set
            {
                this.cinsiyetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public TarihBilgisi DogumTarih
        {
            get
            {
                return this.dogumTarihField;
            }
            set
            {
                this.dogumTarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DogumYer
        {
            get
            {
                return this.dogumYerField;
            }
            set
            {
                this.dogumYerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Soyad
        {
            get
            {
                return this.soyadField;
            }
            set
            {
                this.soyadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OlayTarihBilgisi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private TarihBilgisi bosanmaTarihField;
        
        private TarihBilgisi evlenmeTarihField;
        
        private TarihBilgisi tescilTarihField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TarihBilgisi BosanmaTarih
        {
            get
            {
                return this.bosanmaTarihField;
            }
            set
            {
                this.bosanmaTarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TarihBilgisi EvlenmeTarih
        {
            get
            {
                return this.evlenmeTarihField;
            }
            set
            {
                this.evlenmeTarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TarihBilgisi TescilTarih
        {
            get
            {
                return this.tescilTarihField;
            }
            set
            {
                this.tescilTarihField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KisiKayitYeriBilgisi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> aileSiraNoField;
        
        private System.Nullable<int> bireySiraNoField;
        
        private Parametre ciltField;
        
        private Parametre ilField;
        
        private Parametre ilceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> AileSiraNo
        {
            get
            {
                return this.aileSiraNoField;
            }
            set
            {
                this.aileSiraNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> BireySiraNo
        {
            get
            {
                return this.bireySiraNoField;
            }
            set
            {
                this.bireySiraNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Parametre Cilt
        {
            get
            {
                return this.ciltField;
            }
            set
            {
                this.ciltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Parametre Il
        {
            get
            {
                return this.ilField;
            }
            set
            {
                this.ilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Parametre Ilce
        {
            get
            {
                return this.ilceField;
            }
            set
            {
                this.ilceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KisiDurumBilgisi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private Parametre dinField;
        
        private Parametre durumField;
        
        private Parametre medeniHalField;
        
        private TarihBilgisi olumTarihField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Parametre Din
        {
            get
            {
                return this.dinField;
            }
            set
            {
                this.dinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Parametre Durum
        {
            get
            {
                return this.durumField;
            }
            set
            {
                this.durumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Parametre MedeniHal
        {
            get
            {
                return this.medeniHalField;
            }
            set
            {
                this.medeniHalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TarihBilgisi OlumTarih
        {
            get
            {
                return this.olumTarihField;
            }
            set
            {
                this.olumTarihField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NkoKisi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private KisiDurumBilgisi durumBilgisiField;
        
        private Parametre hataBilgisiField;
        
        private KisiKayitYeriBilgisi kayitYeriBilgisiField;
        
        private OlayTarihBilgisi kisiOlayTarihBilgisiField;
        
        private System.Nullable<long> tCKimlikNoField;
        
        private KisiTemelBilgisi temelBilgisiField;
        
        private Parametre yakinlikKodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public KisiDurumBilgisi DurumBilgisi
        {
            get
            {
                return this.durumBilgisiField;
            }
            set
            {
                this.durumBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public KisiKayitYeriBilgisi KayitYeriBilgisi
        {
            get
            {
                return this.kayitYeriBilgisiField;
            }
            set
            {
                this.kayitYeriBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public OlayTarihBilgisi KisiOlayTarihBilgisi
        {
            get
            {
                return this.kisiOlayTarihBilgisiField;
            }
            set
            {
                this.kisiOlayTarihBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<long> TCKimlikNo
        {
            get
            {
                return this.tCKimlikNoField;
            }
            set
            {
                this.tCKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public KisiTemelBilgisi TemelBilgisi
        {
            get
            {
                return this.temelBilgisiField;
            }
            set
            {
                this.temelBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Parametre YakinlikKod
        {
            get
            {
                return this.yakinlikKodField;
            }
            set
            {
                this.yakinlikKodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Nko
    {
        
        private ExtensionDataObject extensionDataField;
        
        private Parametre hataBilgisiField;
        
        private NkoKisi[] kisilerField;
        
        private Parametre nkoTuruField;
        
        private NkoOlay[] olaylarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public NkoKisi[] Kisiler
        {
            get
            {
                return this.kisilerField;
            }
            set
            {
                this.kisilerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Parametre NkoTuru
        {
            get
            {
                return this.nkoTuruField;
            }
            set
            {
                this.nkoTuruField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public NkoOlay[] Olaylar
        {
            get
            {
                return this.olaylarField;
            }
            set
            {
                this.olaylarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NkoSonucu
    {
        
        private ExtensionDataObject extensionDataField;
        
        private Parametre hataBilgisiField;
        
        private Nko[] sorguSonucuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Nko[] SorguSonucu
        {
            get
            {
                return this.sorguSonucuField;
            }
            set
            {
                this.sorguSonucuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NkoTCKimlikNoSorguKriteri
    {
        
        private ExtensionDataObject extensionDataField;
        
        private System.Nullable<bool> eskiEsListeleField;
        
        private System.Nullable<NkoTur> nKOTipiField;
        
        private System.Nullable<long> tCKimlikNoField;
        
        private System.Nullable<bool> vukuatliField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<bool> EskiEsListele
        {
            get
            {
                return this.eskiEsListeleField;
            }
            set
            {
                this.eskiEsListeleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<NkoTur> NKOTipi
        {
            get
            {
                return this.nKOTipiField;
            }
            set
            {
                this.nKOTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<long> TCKimlikNo
        {
            get
            {
                return this.tCKimlikNoField;
            }
            set
            {
                this.tCKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<bool> Vukuatli
        {
            get
            {
                return this.vukuatliField;
            }
            set
            {
                this.vukuatliField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum NkoTur
    {
        
        /// <remarks/>
        KisiKayitOrnek,
        
        /// <remarks/>
        AileKayitOrnek,
        
        /// <remarks/>
        NufusAileKayitOrnek,
        
        /// <remarks/>
        NufusAileKayitOrnekKardesDahil,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sorgula", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SorgulaRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public MernisTc.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MernisTc.NkoTCKimlikNoSorguKriteri[] KriterList;
        
        public SorgulaRequest()
        {
        }
        
        public SorgulaRequest(MernisTc.AuthHeader AuthHeader, MernisTc.NkoTCKimlikNoSorguKriteri[] KriterList)
        {
            this.AuthHeader = AuthHeader;
            this.KriterList = KriterList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SorgulaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SorgulaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MernisTc.NkoSonucu SorgulaResult;
        
        public SorgulaResponse()
        {
        }
        
        public SorgulaResponse(MernisTc.NkoSonucu SorgulaResult)
        {
            this.SorgulaResult = SorgulaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface NkoSorgulaTCKimlikNoServisSoapChannel : MernisTc.NkoSorgulaTCKimlikNoServisSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class NkoSorgulaTCKimlikNoServisSoapClient : System.ServiceModel.ClientBase<MernisTc.NkoSorgulaTCKimlikNoServisSoap>, MernisTc.NkoSorgulaTCKimlikNoServisSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NkoSorgulaTCKimlikNoServisSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(NkoSorgulaTCKimlikNoServisSoapClient.GetBindingForEndpoint(endpointConfiguration), NkoSorgulaTCKimlikNoServisSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NkoSorgulaTCKimlikNoServisSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NkoSorgulaTCKimlikNoServisSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NkoSorgulaTCKimlikNoServisSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NkoSorgulaTCKimlikNoServisSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NkoSorgulaTCKimlikNoServisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MernisTc.SorgulaResponse> MernisTc.NkoSorgulaTCKimlikNoServisSoap.SorgulaAsync(MernisTc.SorgulaRequest request)
        {
            return base.Channel.SorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<MernisTc.SorgulaResponse> SorgulaAsync(MernisTc.AuthHeader AuthHeader, MernisTc.NkoTCKimlikNoSorguKriteri[] KriterList)
        {
            MernisTc.SorgulaRequest inValue = new MernisTc.SorgulaRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.KriterList = KriterList;
            return ((MernisTc.NkoSorgulaTCKimlikNoServisSoap)(this)).SorgulaAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<MernisTc.NkoSonucu> SorgulaMPAsync(MernisTc.NkoTCKimlikNoSorguKriteri[] KriterList, string uName, string pwd, string sessionID, string SorgulayanKullanici)
        {
            return base.Channel.SorgulaMPAsync(KriterList, uName, pwd, sessionID, SorgulayanKullanici);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NkoSorgulaTCKimlikNoServisSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.NkoSorgulaTCKimlikNoServisSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NkoSorgulaTCKimlikNoServisSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://wsint130.ailevecalisma.gov.tr:8007/NkoSorgulaTCKimlikNo.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.NkoSorgulaTCKimlikNoServisSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://wsint130.ailevecalisma.gov.tr:8007/NkoSorgulaTCKimlikNo.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            NkoSorgulaTCKimlikNoServisSoap,
            
            NkoSorgulaTCKimlikNoServisSoap12,
        }
    }
}
