//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOsym
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TOsym.OSYMSoap")]
    public interface OSYMSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SonucGruplariniGetir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServisSonuc))]
        TOsym.SonucGruplariniGetirResponse SonucGruplariniGetir(TOsym.SonucGruplariniGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SonucGruplariniGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<TOsym.SonucGruplariniGetirResponse> SonucGruplariniGetirAsync(TOsym.SonucGruplariniGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SonucGetir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServisSonuc))]
        TOsym.SonucGetirResponse SonucGetir(TOsym.SonucGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SonucGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<TOsym.SonucGetirResponse> SonucGetirAsync(TOsym.SonucGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SonucGetirXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServisSonuc))]
        TOsym.SonucGetirXmlResponse SonucGetirXml(TOsym.SonucGetirXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SonucGetirXml", ReplyAction="*")]
        System.Threading.Tasks.Task<TOsym.SonucGetirXmlResponse> SonucGetirXmlAsync(TOsym.SonucGetirXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SonucGetirHtml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServisSonuc))]
        TOsym.SonucGetirHtmlResponse SonucGetirHtml(TOsym.SonucGetirHtmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SonucGetirHtml", ReplyAction="*")]
        System.Threading.Tasks.Task<TOsym.SonucGetirHtmlResponse> SonucGetirHtmlAsync(TOsym.SonucGetirHtmlRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader
    {
        
        private string usernameField;
        
        private string passwordField;
        
        private string sessionIDField;
        
        private string kullaniciBilgisiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SessionID
        {
            get
            {
                return this.sessionIDField;
            }
            set
            {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string KullaniciBilgisi
        {
            get
            {
                return this.kullaniciBilgisiField;
            }
            set
            {
                this.kullaniciBilgisiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SonucBilgiHtml
    {
        
        private ExtensionDataObject extensionDataField;
        
        private System.DateTime aciklamaTarihiField;
        
        private string sonucAdField;
        
        private byte[] sonucHtmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime AciklamaTarihi
        {
            get
            {
                return this.aciklamaTarihiField;
            }
            set
            {
                this.aciklamaTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SonucAd
        {
            get
            {
                return this.sonucAdField;
            }
            set
            {
                this.sonucAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] SonucHtml
        {
            get
            {
                return this.sonucHtmlField;
            }
            set
            {
                this.sonucHtmlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExtensionDataObject
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SonucBilgiXml
    {
        
        private ExtensionDataObject extensionDataField;
        
        private System.DateTime aciklamaTarihiField;
        
        private string sonucAdField;
        
        private string xmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime AciklamaTarihi
        {
            get
            {
                return this.aciklamaTarihiField;
            }
            set
            {
                this.aciklamaTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SonucAd
        {
            get
            {
                return this.sonucAdField;
            }
            set
            {
                this.sonucAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SinavSonucTemelBilgi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private System.DateTime aciklamaTarihiField;
        
        private string adField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime AciklamaTarihi
        {
            get
            {
                return this.aciklamaTarihiField;
            }
            set
            {
                this.aciklamaTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Ad
        {
            get
            {
                return this.adField;
            }
            set
            {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SinavGrupBilgi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string adField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ad
        {
            get
            {
                return this.adField;
            }
            set
            {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServisSonucOfSonucBilgiHtmlYKHEH_S_P5))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServisSonucOfSonucBilgiXmlYKHEH_S_P5))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServisSonucOfArrayOfSinavSonucTemelBilgiYKHEH_S_P5))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServisSonucOfArrayOfSinavGrupBilgiYKHEH_S_P5))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServisSonuc
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string aciklamaField;
        
        private SonucKodu sonucKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Aciklama
        {
            get
            {
                return this.aciklamaField;
            }
            set
            {
                this.aciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SonucKodu SonucKodu
        {
            get
            {
                return this.sonucKoduField;
            }
            set
            {
                this.sonucKoduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SonucKodu
    {
        
        /// <remarks/>
        KayitBulunamadi,
        
        /// <remarks/>
        Basarili,
        
        /// <remarks/>
        GecersizVeri,
        
        /// <remarks/>
        YetkisizIslem,
        
        /// <remarks/>
        ZamanAsimi,
        
        /// <remarks/>
        BeklenmeyenHata,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServisSonucOfSonucBilgiHtmlYKHEH_S_P5 : ServisSonuc
    {
        
        private SonucBilgiHtml sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SonucBilgiHtml Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServisSonucOfSonucBilgiXmlYKHEH_S_P5 : ServisSonuc
    {
        
        private SonucBilgiXml sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SonucBilgiXml Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServisSonucOfArrayOfSinavSonucTemelBilgiYKHEH_S_P5 : ServisSonuc
    {
        
        private SinavSonucTemelBilgi[] sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public SinavSonucTemelBilgi[] Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServisSonucOfArrayOfSinavGrupBilgiYKHEH_S_P5 : ServisSonuc
    {
        
        private SinavGrupBilgi[] sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public SinavGrupBilgi[] Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SonucGruplariniGetir", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SonucGruplariniGetirRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TOsym.AuthHeader AuthHeader;
        
        public SonucGruplariniGetirRequest()
        {
        }
        
        public SonucGruplariniGetirRequest(TOsym.AuthHeader AuthHeader)
        {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SonucGruplariniGetirResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SonucGruplariniGetirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TOsym.ServisSonucOfArrayOfSinavGrupBilgiYKHEH_S_P5 SonucGruplariniGetirResult;
        
        public SonucGruplariniGetirResponse()
        {
        }
        
        public SonucGruplariniGetirResponse(TOsym.ServisSonucOfArrayOfSinavGrupBilgiYKHEH_S_P5 SonucGruplariniGetirResult)
        {
            this.SonucGruplariniGetirResult = SonucGruplariniGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SonucGetir", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SonucGetirRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TOsym.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string tcKimlikNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int sinavYili;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int sinavGrupId;
        
        public SonucGetirRequest()
        {
        }
        
        public SonucGetirRequest(TOsym.AuthHeader AuthHeader, string tcKimlikNo, int sinavYili, int sinavGrupId)
        {
            this.AuthHeader = AuthHeader;
            this.tcKimlikNo = tcKimlikNo;
            this.sinavYili = sinavYili;
            this.sinavGrupId = sinavGrupId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SonucGetirResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SonucGetirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TOsym.ServisSonucOfArrayOfSinavSonucTemelBilgiYKHEH_S_P5 SonucGetirResult;
        
        public SonucGetirResponse()
        {
        }
        
        public SonucGetirResponse(TOsym.ServisSonucOfArrayOfSinavSonucTemelBilgiYKHEH_S_P5 SonucGetirResult)
        {
            this.SonucGetirResult = SonucGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SonucGetirXml", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SonucGetirXmlRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TOsym.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string tcKimlikNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int sonucId;
        
        public SonucGetirXmlRequest()
        {
        }
        
        public SonucGetirXmlRequest(TOsym.AuthHeader AuthHeader, string tcKimlikNo, int sonucId)
        {
            this.AuthHeader = AuthHeader;
            this.tcKimlikNo = tcKimlikNo;
            this.sonucId = sonucId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SonucGetirXmlResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SonucGetirXmlResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TOsym.ServisSonucOfSonucBilgiXmlYKHEH_S_P5 SonucGetirXmlResult;
        
        public SonucGetirXmlResponse()
        {
        }
        
        public SonucGetirXmlResponse(TOsym.ServisSonucOfSonucBilgiXmlYKHEH_S_P5 SonucGetirXmlResult)
        {
            this.SonucGetirXmlResult = SonucGetirXmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SonucGetirHtml", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SonucGetirHtmlRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TOsym.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string tcKimlikNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int sonucId;
        
        public SonucGetirHtmlRequest()
        {
        }
        
        public SonucGetirHtmlRequest(TOsym.AuthHeader AuthHeader, string tcKimlikNo, int sonucId)
        {
            this.AuthHeader = AuthHeader;
            this.tcKimlikNo = tcKimlikNo;
            this.sonucId = sonucId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SonucGetirHtmlResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SonucGetirHtmlResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TOsym.ServisSonucOfSonucBilgiHtmlYKHEH_S_P5 SonucGetirHtmlResult;
        
        public SonucGetirHtmlResponse()
        {
        }
        
        public SonucGetirHtmlResponse(TOsym.ServisSonucOfSonucBilgiHtmlYKHEH_S_P5 SonucGetirHtmlResult)
        {
            this.SonucGetirHtmlResult = SonucGetirHtmlResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface OSYMSoapChannel : TOsym.OSYMSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class OSYMSoapClient : System.ServiceModel.ClientBase<TOsym.OSYMSoap>, TOsym.OSYMSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OSYMSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(OSYMSoapClient.GetBindingForEndpoint(endpointConfiguration), OSYMSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OSYMSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OSYMSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OSYMSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OSYMSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OSYMSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public TOsym.SonucGruplariniGetirResponse SonucGruplariniGetir(TOsym.SonucGruplariniGetirRequest request)
        {
            return base.Channel.SonucGruplariniGetir(request);
        }
        
        public System.Threading.Tasks.Task<TOsym.SonucGruplariniGetirResponse> SonucGruplariniGetirAsync(TOsym.SonucGruplariniGetirRequest request)
        {
            return base.Channel.SonucGruplariniGetirAsync(request);
        }
        
        public TOsym.SonucGetirResponse SonucGetir(TOsym.SonucGetirRequest request)
        {
            return base.Channel.SonucGetir(request);
        }
        
        public System.Threading.Tasks.Task<TOsym.SonucGetirResponse> SonucGetirAsync(TOsym.SonucGetirRequest request)
        {
            return base.Channel.SonucGetirAsync(request);
        }
        
        public TOsym.SonucGetirXmlResponse SonucGetirXml(TOsym.SonucGetirXmlRequest request)
        {
            return base.Channel.SonucGetirXml(request);
        }
        
        public System.Threading.Tasks.Task<TOsym.SonucGetirXmlResponse> SonucGetirXmlAsync(TOsym.SonucGetirXmlRequest request)
        {
            return base.Channel.SonucGetirXmlAsync(request);
        }
        
        public TOsym.SonucGetirHtmlResponse SonucGetirHtml(TOsym.SonucGetirHtmlRequest request)
        {
            return base.Channel.SonucGetirHtml(request);
        }
        
        public System.Threading.Tasks.Task<TOsym.SonucGetirHtmlResponse> SonucGetirHtmlAsync(TOsym.SonucGetirHtmlRequest request)
        {
            return base.Channel.SonucGetirHtmlAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OSYMSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.OSYMSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OSYMSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://wsint130.ailevecalisma.gov.tr:8012/TOsym.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.OSYMSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://wsint130.ailevecalisma.gov.tr:8012/TOsym.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            OSYMSoap,
            
            OSYMSoap12,
        }
    }
}
