//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobWcfService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="iseAlimTalebi", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.JobService")]
    public partial class iseAlimTalebi : JobWcfService.abstractHumanResourcesTransferableEntity
    {
        
        private string aciklamaFieldField;
        
        private int alinacakKisiSayisiFieldField;
        
        private bool alinacakKisiSayisiFieldSpecifiedField;
        
        private string baslikFieldField;
        
        private System.DateTime basvuruBaslangicZamaniFieldField;
        
        private bool basvuruBaslangicZamaniFieldSpecifiedField;
        
        private System.DateTime basvuruBitisZamaniFieldField;
        
        private bool basvuruBitisZamaniFieldSpecifiedField;
        
        private System.DateTime belgeTeslimTarihiFieldField;
        
        private bool belgeTeslimTarihiFieldSpecifiedField;
        
        private string bilgisayarBilgisiAciklamasiFieldField;
        
        private bool bilgisayarBilgisiGerekliFieldField;
        
        private bool bilgisayarBilgisiGerekliFieldSpecifiedField;
        
        private string bolumAciklamasiFieldField;
        
        private bool bolumGerekliFieldField;
        
        private bool bolumGerekliFieldSpecifiedField;
        
        private JobWcfService.calismaSekli calismaSekliFieldField;
        
        private bool calismaSekliFieldSpecifiedField;
        
        private JobWcfService.ilBilgisi cityFieldField;
        
        private string dilAciklamasiFieldField;
        
        private bool dilGerekliFieldField;
        
        private bool dilGerekliFieldSpecifiedField;
        
        private JobWcfService.ilceBilgisi districtFieldField;
        
        private JobWcfService.iseAlimTalebiDurumu durumFieldField;
        
        private bool durumFieldSpecifiedField;
        
        private bool ilGerekliFieldField;
        
        private bool ilGerekliFieldSpecifiedField;
        
        private bool ilceGerekliFieldField;
        
        private bool ilceGerekliFieldSpecifiedField;
        
        private long iseAlimTalebiNoFieldField;
        
        private bool iseAlimTalebiNoFieldSpecifiedField;
        
        private System.DateTime mulakatTarihiFieldField;
        
        private bool mulakatTarihiFieldSpecifiedField;
        
        private string surucuBelgesiAciklamasiFieldField;
        
        private bool surucuBelgesiGerekliFieldField;
        
        private bool surucuBelgesiGerekliFieldSpecifiedField;
        
        private JobWcfService.unvan unvanFieldField;
        
        private bool unvanFieldSpecifiedField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string aciklamaField
        {
            get
            {
                return this.aciklamaFieldField;
            }
            set
            {
                this.aciklamaFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int alinacakKisiSayisiField
        {
            get
            {
                return this.alinacakKisiSayisiFieldField;
            }
            set
            {
                this.alinacakKisiSayisiFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool alinacakKisiSayisiFieldSpecified
        {
            get
            {
                return this.alinacakKisiSayisiFieldSpecifiedField;
            }
            set
            {
                this.alinacakKisiSayisiFieldSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string baslikField
        {
            get
            {
                return this.baslikFieldField;
            }
            set
            {
                this.baslikFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime basvuruBaslangicZamaniField
        {
            get
            {
                return this.basvuruBaslangicZamaniFieldField;
            }
            set
            {
                this.basvuruBaslangicZamaniFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool basvuruBaslangicZamaniFieldSpecified
        {
            get
            {
                return this.basvuruBaslangicZamaniFieldSpecifiedField;
            }
            set
            {
                this.basvuruBaslangicZamaniFieldSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime basvuruBitisZamaniField
        {
            get
            {
                return this.basvuruBitisZamaniFieldField;
            }
            set
            {
                this.basvuruBitisZamaniFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool basvuruBitisZamaniFieldSpecified
        {
            get
            {
                return this.basvuruBitisZamaniFieldSpecifiedField;
            }
            set
            {
                this.basvuruBitisZamaniFieldSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime belgeTeslimTarihiField
        {
            get
            {
                return this.belgeTeslimTarihiFieldField;
            }
            set
            {
                this.belgeTeslimTarihiFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool belgeTeslimTarihiFieldSpecified
        {
            get
            {
                return this.belgeTeslimTarihiFieldSpecifiedField;
            }
            set
            {
                this.belgeTeslimTarihiFieldSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string bilgisayarBilgisiAciklamasiField
        {
            get
            {
                return this.bilgisayarBilgisiAciklamasiFieldField;
            }
            set
            {
                this.bilgisayarBilgisiAciklamasiFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool bilgisayarBilgisiGerekliField
        {
            get
            {
                return this.bilgisayarBilgisiGerekliFieldField;
            }
            set
            {
                this.bilgisayarBilgisiGerekliFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool bilgisayarBilgisiGerekliFieldSpecified
        {
            get
            {
                return this.bilgisayarBilgisiGerekliFieldSpecifiedField;
            }
            set
            {
                this.bilgisayarBilgisiGerekliFieldSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string bolumAciklamasiField
        {
            get
            {
                return this.bolumAciklamasiFieldField;
            }
            set
            {
                this.bolumAciklamasiFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool bolumGerekliField
        {
            get
            {
                return this.bolumGerekliFieldField;
            }
            set
            {
                this.bolumGerekliFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool bolumGerekliFieldSpecified
        {
            get
            {
                return this.bolumGerekliFieldSpecifiedField;
            }
            set
            {
                this.bolumGerekliFieldSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public JobWcfService.calismaSekli calismaSekliField
        {
            get
            {
                return this.calismaSekliFieldField;
            }
            set
            {
                this.calismaSekliFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool calismaSekliFieldSpecified
        {
            get
            {
                return this.calismaSekliFieldSpecifiedField;
            }
            set
            {
                this.calismaSekliFieldSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public JobWcfService.ilBilgisi cityField
        {
            get
            {
                return this.cityFieldField;
            }
            set
            {
                this.cityFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string dilAciklamasiField
        {
            get
            {
                return this.dilAciklamasiFieldField;
            }
            set
            {
                this.dilAciklamasiFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool dilGerekliField
        {
            get
            {
                return this.dilGerekliFieldField;
            }
            set
            {
                this.dilGerekliFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool dilGerekliFieldSpecified
        {
            get
            {
                return this.dilGerekliFieldSpecifiedField;
            }
            set
            {
                this.dilGerekliFieldSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public JobWcfService.ilceBilgisi districtField
        {
            get
            {
                return this.districtFieldField;
            }
            set
            {
                this.districtFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public JobWcfService.iseAlimTalebiDurumu durumField
        {
            get
            {
                return this.durumFieldField;
            }
            set
            {
                this.durumFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool durumFieldSpecified
        {
            get
            {
                return this.durumFieldSpecifiedField;
            }
            set
            {
                this.durumFieldSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ilGerekliField
        {
            get
            {
                return this.ilGerekliFieldField;
            }
            set
            {
                this.ilGerekliFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ilGerekliFieldSpecified
        {
            get
            {
                return this.ilGerekliFieldSpecifiedField;
            }
            set
            {
                this.ilGerekliFieldSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ilceGerekliField
        {
            get
            {
                return this.ilceGerekliFieldField;
            }
            set
            {
                this.ilceGerekliFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ilceGerekliFieldSpecified
        {
            get
            {
                return this.ilceGerekliFieldSpecifiedField;
            }
            set
            {
                this.ilceGerekliFieldSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long iseAlimTalebiNoField
        {
            get
            {
                return this.iseAlimTalebiNoFieldField;
            }
            set
            {
                this.iseAlimTalebiNoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool iseAlimTalebiNoFieldSpecified
        {
            get
            {
                return this.iseAlimTalebiNoFieldSpecifiedField;
            }
            set
            {
                this.iseAlimTalebiNoFieldSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime mulakatTarihiField
        {
            get
            {
                return this.mulakatTarihiFieldField;
            }
            set
            {
                this.mulakatTarihiFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool mulakatTarihiFieldSpecified
        {
            get
            {
                return this.mulakatTarihiFieldSpecifiedField;
            }
            set
            {
                this.mulakatTarihiFieldSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string surucuBelgesiAciklamasiField
        {
            get
            {
                return this.surucuBelgesiAciklamasiFieldField;
            }
            set
            {
                this.surucuBelgesiAciklamasiFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool surucuBelgesiGerekliField
        {
            get
            {
                return this.surucuBelgesiGerekliFieldField;
            }
            set
            {
                this.surucuBelgesiGerekliFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool surucuBelgesiGerekliFieldSpecified
        {
            get
            {
                return this.surucuBelgesiGerekliFieldSpecifiedField;
            }
            set
            {
                this.surucuBelgesiGerekliFieldSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public JobWcfService.unvan unvanField
        {
            get
            {
                return this.unvanFieldField;
            }
            set
            {
                this.unvanFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool unvanFieldSpecified
        {
            get
            {
                return this.unvanFieldSpecifiedField;
            }
            set
            {
                this.unvanFieldSpecifiedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="abstractHumanResourcesTransferableEntity", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.JobService")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JobWcfService.ilBilgisi))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JobWcfService.ilceBilgisi))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JobWcfService.IsBasvurusu))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JobWcfService.IsBasvurusuDigerBilgiler))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JobWcfService.IsBasvurusuKisiselBilgiler))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JobWcfService.islemSonucu))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JobWcfService.mesaj))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JobWcfService.KisiIseAlimTalebi))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JobWcfService.iseAlimTalebi))]
    public partial class abstractHumanResourcesTransferableEntity : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ilBilgisi", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.JobService")]
    public partial class ilBilgisi : JobWcfService.abstractHumanResourcesTransferableEntity
    {
        
        private string ilAdiFieldField;
        
        private short mernisIlKoduFieldField;
        
        private bool mernisIlKoduFieldSpecifiedField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ilAdiField
        {
            get
            {
                return this.ilAdiFieldField;
            }
            set
            {
                this.ilAdiFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short mernisIlKoduField
        {
            get
            {
                return this.mernisIlKoduFieldField;
            }
            set
            {
                this.mernisIlKoduFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool mernisIlKoduFieldSpecified
        {
            get
            {
                return this.mernisIlKoduFieldSpecifiedField;
            }
            set
            {
                this.mernisIlKoduFieldSpecifiedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ilceBilgisi", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.JobService")]
    public partial class ilceBilgisi : JobWcfService.abstractHumanResourcesTransferableEntity
    {
        
        private string ilceAdiFieldField;
        
        private int mernisIlceKoduFieldField;
        
        private bool mernisIlceKoduFieldSpecifiedField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ilceAdiField
        {
            get
            {
                return this.ilceAdiFieldField;
            }
            set
            {
                this.ilceAdiFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int mernisIlceKoduField
        {
            get
            {
                return this.mernisIlceKoduFieldField;
            }
            set
            {
                this.mernisIlceKoduFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool mernisIlceKoduFieldSpecified
        {
            get
            {
                return this.mernisIlceKoduFieldSpecifiedField;
            }
            set
            {
                this.mernisIlceKoduFieldSpecifiedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IsBasvurusu", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.JobService")]
    public partial class IsBasvurusu : JobWcfService.abstractHumanResourcesTransferableEntity
    {
        
        private JobWcfService.IsBasvurusuDigerBilgiler digerBilgilerFieldField;
        
        private JobWcfService.IsBasvurusuKisiselBilgiler kisiselBilgilerFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public JobWcfService.IsBasvurusuDigerBilgiler digerBilgilerField
        {
            get
            {
                return this.digerBilgilerFieldField;
            }
            set
            {
                this.digerBilgilerFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public JobWcfService.IsBasvurusuKisiselBilgiler kisiselBilgilerField
        {
            get
            {
                return this.kisiselBilgilerFieldField;
            }
            set
            {
                this.kisiselBilgilerFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IsBasvurusuDigerBilgiler", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.JobService")]
    public partial class IsBasvurusuDigerBilgiler : JobWcfService.abstractHumanResourcesTransferableEntity
    {
        
        private JobWcfService.askerlikDurumu askerlikDurumuFieldField;
        
        private string cepTelNumarasiFieldField;
        
        private string digerBilgilerFieldField;
        
        private string ePostaFieldField;
        
        private JobWcfService.egitimDurumu egitimDurumuFieldField;
        
        private bool egitimDurumuFieldSpecifiedField;
        
        private string evTelNumarasiFieldField;
        
        private string isTelNumarasiFieldField;
        
        private int kpssGirisYiliFieldField;
        
        private double kpssPuaniFieldField;
        
        private System.DateTime mezuniyetTarihiFieldField;
        
        private bool mezuniyetTarihiFieldSpecifiedField;
        
        private System.DateTime tecilTarihiFieldField;
        
        private bool tecilTarihiFieldSpecifiedField;
        
        private string universiteBolumuFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public JobWcfService.askerlikDurumu askerlikDurumuField
        {
            get
            {
                return this.askerlikDurumuFieldField;
            }
            set
            {
                this.askerlikDurumuFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cepTelNumarasiField
        {
            get
            {
                return this.cepTelNumarasiFieldField;
            }
            set
            {
                this.cepTelNumarasiFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string digerBilgilerField
        {
            get
            {
                return this.digerBilgilerFieldField;
            }
            set
            {
                this.digerBilgilerFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ePostaField
        {
            get
            {
                return this.ePostaFieldField;
            }
            set
            {
                this.ePostaFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public JobWcfService.egitimDurumu egitimDurumuField
        {
            get
            {
                return this.egitimDurumuFieldField;
            }
            set
            {
                this.egitimDurumuFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool egitimDurumuFieldSpecified
        {
            get
            {
                return this.egitimDurumuFieldSpecifiedField;
            }
            set
            {
                this.egitimDurumuFieldSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string evTelNumarasiField
        {
            get
            {
                return this.evTelNumarasiFieldField;
            }
            set
            {
                this.evTelNumarasiFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string isTelNumarasiField
        {
            get
            {
                return this.isTelNumarasiFieldField;
            }
            set
            {
                this.isTelNumarasiFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int kpssGirisYiliField
        {
            get
            {
                return this.kpssGirisYiliFieldField;
            }
            set
            {
                this.kpssGirisYiliFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double kpssPuaniField
        {
            get
            {
                return this.kpssPuaniFieldField;
            }
            set
            {
                this.kpssPuaniFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime mezuniyetTarihiField
        {
            get
            {
                return this.mezuniyetTarihiFieldField;
            }
            set
            {
                this.mezuniyetTarihiFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool mezuniyetTarihiFieldSpecified
        {
            get
            {
                return this.mezuniyetTarihiFieldSpecifiedField;
            }
            set
            {
                this.mezuniyetTarihiFieldSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime tecilTarihiField
        {
            get
            {
                return this.tecilTarihiFieldField;
            }
            set
            {
                this.tecilTarihiFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool tecilTarihiFieldSpecified
        {
            get
            {
                return this.tecilTarihiFieldSpecifiedField;
            }
            set
            {
                this.tecilTarihiFieldSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string universiteBolumuField
        {
            get
            {
                return this.universiteBolumuFieldField;
            }
            set
            {
                this.universiteBolumuFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IsBasvurusuKisiselBilgiler", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.JobService")]
    public partial class IsBasvurusuKisiselBilgiler : JobWcfService.abstractHumanResourcesTransferableEntity
    {
        
        private string adFieldField;
        
        private JobWcfService.cinsiyet cinsiyetFieldField;
        
        private System.DateTime dogumTarihiFieldField;
        
        private string dogumYeriFieldField;
        
        private JobWcfService.ilceBilgisi ilceFieldField;
        
        private JobWcfService.medeniDurumu medeniDurumuFieldField;
        
        private string soyadFieldField;
        
        private string tcKimlikNoFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string adField
        {
            get
            {
                return this.adFieldField;
            }
            set
            {
                this.adFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public JobWcfService.cinsiyet cinsiyetField
        {
            get
            {
                return this.cinsiyetFieldField;
            }
            set
            {
                this.cinsiyetFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime dogumTarihiField
        {
            get
            {
                return this.dogumTarihiFieldField;
            }
            set
            {
                this.dogumTarihiFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string dogumYeriField
        {
            get
            {
                return this.dogumYeriFieldField;
            }
            set
            {
                this.dogumYeriFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public JobWcfService.ilceBilgisi ilceField
        {
            get
            {
                return this.ilceFieldField;
            }
            set
            {
                this.ilceFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public JobWcfService.medeniDurumu medeniDurumuField
        {
            get
            {
                return this.medeniDurumuFieldField;
            }
            set
            {
                this.medeniDurumuFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string soyadField
        {
            get
            {
                return this.soyadFieldField;
            }
            set
            {
                this.soyadFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tcKimlikNoField
        {
            get
            {
                return this.tcKimlikNoFieldField;
            }
            set
            {
                this.tcKimlikNoFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="islemSonucu", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.JobService")]
    public partial class islemSonucu : JobWcfService.abstractHumanResourcesTransferableEntity
    {
        
        private JobWcfService.mesaj mesajFieldField;
        
        private JobWcfService.sonucTuru sonucTuruFieldField;
        
        private bool sonucTuruFieldSpecifiedField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public JobWcfService.mesaj mesajField
        {
            get
            {
                return this.mesajFieldField;
            }
            set
            {
                this.mesajFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public JobWcfService.sonucTuru sonucTuruField
        {
            get
            {
                return this.sonucTuruFieldField;
            }
            set
            {
                this.sonucTuruFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool sonucTuruFieldSpecified
        {
            get
            {
                return this.sonucTuruFieldSpecifiedField;
            }
            set
            {
                this.sonucTuruFieldSpecifiedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="mesaj", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.JobService")]
    public partial class mesaj : JobWcfService.abstractHumanResourcesTransferableEntity
    {
        
        private int adetFieldField;
        
        private string mesaj1FieldField;
        
        private string mesajKoduFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int adetField
        {
            get
            {
                return this.adetFieldField;
            }
            set
            {
                this.adetFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string mesaj1Field
        {
            get
            {
                return this.mesaj1FieldField;
            }
            set
            {
                this.mesaj1FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string mesajKoduField
        {
            get
            {
                return this.mesajKoduFieldField;
            }
            set
            {
                this.mesajKoduFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiIseAlimTalebi", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.JobService")]
    public partial class KisiIseAlimTalebi : JobWcfService.abstractHumanResourcesTransferableEntity
    {
        
        private string basvuruDurumuFieldField;
        
        private System.DateTime basvuruTarihiFieldField;
        
        private bool basvuruTarihiFieldSpecifiedField;
        
        private JobWcfService.iseAlimTalebi iseAlimTalebiFieldField;
        
        private long iseBasvurusuNoFieldField;
        
        private bool iseBasvurusuNoFieldSpecifiedField;
        
        private string tcKimlikNoFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string basvuruDurumuField
        {
            get
            {
                return this.basvuruDurumuFieldField;
            }
            set
            {
                this.basvuruDurumuFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime basvuruTarihiField
        {
            get
            {
                return this.basvuruTarihiFieldField;
            }
            set
            {
                this.basvuruTarihiFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool basvuruTarihiFieldSpecified
        {
            get
            {
                return this.basvuruTarihiFieldSpecifiedField;
            }
            set
            {
                this.basvuruTarihiFieldSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public JobWcfService.iseAlimTalebi iseAlimTalebiField
        {
            get
            {
                return this.iseAlimTalebiFieldField;
            }
            set
            {
                this.iseAlimTalebiFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long iseBasvurusuNoField
        {
            get
            {
                return this.iseBasvurusuNoFieldField;
            }
            set
            {
                this.iseBasvurusuNoFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool iseBasvurusuNoFieldSpecified
        {
            get
            {
                return this.iseBasvurusuNoFieldSpecifiedField;
            }
            set
            {
                this.iseBasvurusuNoFieldSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tcKimlikNoField
        {
            get
            {
                return this.tcKimlikNoFieldField;
            }
            set
            {
                this.tcKimlikNoFieldField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="calismaSekli", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.JobService")]
    public enum calismaSekli : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BELIRSIZ_SURELI = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BELIRLI_SURELI = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GOREVLENDIRME = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="iseAlimTalebiDurumu", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.JobService")]
    public enum iseAlimTalebiDurumu : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AKTIF = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PASIF = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="unvan", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.JobService")]
    public enum unvan : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VAKIF_MUDURU = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MUHASEBECI = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SOSYAL_YARDIM_VE_INCELEME_GOREVLISI = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BURO_GOREVLISI = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YARDIMCI_HIZMET_GOREVLISI = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GECICI_PERSONEL = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="askerlikDurumu", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.JobService")]
    public enum askerlikDurumu : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YAPTI = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TECILLI = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MUAF = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GECERSIZ = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="egitimDurumu", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.JobService")]
    public enum egitimDurumu : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BILINMIYOR = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OKUR_YAZAR_DEGIL = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OKUR_YAZAR = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OKUR_YAZAR_ILKOGRETIM_TERK = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ILKOKUL = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ORTAOKUL = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ILKOGRETIM = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LISE = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LISE_TERK = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ON_LISANS = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNIVERSITE_TERK = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNIVERSITE = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YUKSEK_LISANS = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOKTORA = 13,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cinsiyet", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.JobService")]
    public enum cinsiyet : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KADIN = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERKEK = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BILINMIYOR = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="medeniDurumu", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.JobService")]
    public enum medeniDurumu : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EVLI = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BEKAR = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BOSANMIS = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DUL = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EVLILIGIN_FESHI = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EVLILIGIN_IPTALI = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BILINMEYEN = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sonucTuru", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.JobService")]
    public enum sonucTuru : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HATA = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UYARI = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BILGI = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ONAY = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    public partial class CompositeType : object
    {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JobWcfService.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        JobWcfService.iseAlimTalebi[] GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<JobWcfService.iseAlimTalebi[]> GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        JobWcfService.CompositeType GetDataUsingDataContract(JobWcfService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<JobWcfService.CompositeType> GetDataUsingDataContractAsync(JobWcfService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isBasvurusuEkleProxy", ReplyAction="http://tempuri.org/IService1/isBasvurusuEkleProxyResponse")]
        JobWcfService.islemSonucu isBasvurusuEkleProxy(JobWcfService.IsBasvurusu isBasvurusu, long ilanNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isBasvurusuEkleProxy", ReplyAction="http://tempuri.org/IService1/isBasvurusuEkleProxyResponse")]
        System.Threading.Tasks.Task<JobWcfService.islemSonucu> isBasvurusuEkleProxyAsync(JobWcfService.IsBasvurusu isBasvurusu, long ilanNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isBasvurusuGuncelleProxy", ReplyAction="http://tempuri.org/IService1/isBasvurusuGuncelleProxyResponse")]
        JobWcfService.islemSonucu isBasvurusuGuncelleProxy(JobWcfService.IsBasvurusuDigerBilgiler isBasvurusu, long basvuruNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isBasvurusuGuncelleProxy", ReplyAction="http://tempuri.org/IService1/isBasvurusuGuncelleProxyResponse")]
        System.Threading.Tasks.Task<JobWcfService.islemSonucu> isBasvurusuGuncelleProxyAsync(JobWcfService.IsBasvurusuDigerBilgiler isBasvurusu, long basvuruNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getBasvurularim", ReplyAction="http://tempuri.org/IService1/getBasvurularimResponse")]
        JobWcfService.KisiIseAlimTalebi[] getBasvurularim(string TCNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getBasvurularim", ReplyAction="http://tempuri.org/IService1/getBasvurularimResponse")]
        System.Threading.Tasks.Task<JobWcfService.KisiIseAlimTalebi[]> getBasvurularimAsync(string TCNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IService1Channel : JobWcfService.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class Service1Client : System.ServiceModel.ClientBase<JobWcfService.IService1>, JobWcfService.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public JobWcfService.iseAlimTalebi[] GetData()
        {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<JobWcfService.iseAlimTalebi[]> GetDataAsync()
        {
            return base.Channel.GetDataAsync();
        }
        
        public JobWcfService.CompositeType GetDataUsingDataContract(JobWcfService.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<JobWcfService.CompositeType> GetDataUsingDataContractAsync(JobWcfService.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public JobWcfService.islemSonucu isBasvurusuEkleProxy(JobWcfService.IsBasvurusu isBasvurusu, long ilanNo)
        {
            return base.Channel.isBasvurusuEkleProxy(isBasvurusu, ilanNo);
        }
        
        public System.Threading.Tasks.Task<JobWcfService.islemSonucu> isBasvurusuEkleProxyAsync(JobWcfService.IsBasvurusu isBasvurusu, long ilanNo)
        {
            return base.Channel.isBasvurusuEkleProxyAsync(isBasvurusu, ilanNo);
        }
        
        public JobWcfService.islemSonucu isBasvurusuGuncelleProxy(JobWcfService.IsBasvurusuDigerBilgiler isBasvurusu, long basvuruNo)
        {
            return base.Channel.isBasvurusuGuncelleProxy(isBasvurusu, basvuruNo);
        }
        
        public System.Threading.Tasks.Task<JobWcfService.islemSonucu> isBasvurusuGuncelleProxyAsync(JobWcfService.IsBasvurusuDigerBilgiler isBasvurusu, long basvuruNo)
        {
            return base.Channel.isBasvurusuGuncelleProxyAsync(isBasvurusu, basvuruNo);
        }
        
        public JobWcfService.KisiIseAlimTalebi[] getBasvurularim(string TCNo)
        {
            return base.Channel.getBasvurularim(TCNo);
        }
        
        public System.Threading.Tasks.Task<JobWcfService.KisiIseAlimTalebi[]> getBasvurularimAsync(string TCNo)
        {
            return base.Channel.getBasvurularimAsync(TCNo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:11331/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
