//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MernisAdres
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MernisAdres.TcKimlikNoSorgulaAdresServisSoap")]
    public interface TcKimlikNoSorgulaAdresServisSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MernisAdres.SorgulaResponse Sorgula(MernisAdres.SorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<MernisAdres.SorgulaResponse> SorgulaAsync(MernisAdres.SorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SorgulaMP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MernisAdres.SorgulaMPResponse SorgulaMP(MernisAdres.SorgulaMPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SorgulaMP", ReplyAction="*")]
        System.Threading.Tasks.Task<MernisAdres.SorgulaMPResponse> SorgulaMPAsync(MernisAdres.SorgulaMPRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader
    {
        
        private string usernameField;
        
        private string passwordField;
        
        private string sessionIDField;
        
        private string sorgulayanKullaniciField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SessionID
        {
            get
            {
                return this.sessionIDField;
            }
            set
            {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SorgulayanKullanici
        {
            get
            {
                return this.sorgulayanKullaniciField;
            }
            set
            {
                this.sorgulayanKullaniciField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KimlikNoileYurtDisiAdresi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private System.Nullable<System.DateTime> disTemsDuzeltmeBeyanTarihField;
        
        private System.Nullable<System.DateTime> disTemsDuzeltmeKararTarihField;
        
        private Parametre disTemsDuzeltmeNedenField;
        
        private Parametre disTemsilcilikField;
        
        private Parametre hataBilgisiField;
        
        private string yabanciAdresField;
        
        private string yabanciSehirField;
        
        private Parametre yabanciUlkeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> DisTemsDuzeltmeBeyanTarih
        {
            get
            {
                return this.disTemsDuzeltmeBeyanTarihField;
            }
            set
            {
                this.disTemsDuzeltmeBeyanTarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> DisTemsDuzeltmeKararTarih
        {
            get
            {
                return this.disTemsDuzeltmeKararTarihField;
            }
            set
            {
                this.disTemsDuzeltmeKararTarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Parametre DisTemsDuzeltmeNeden
        {
            get
            {
                return this.disTemsDuzeltmeNedenField;
            }
            set
            {
                this.disTemsDuzeltmeNedenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Parametre DisTemsilcilik
        {
            get
            {
                return this.disTemsilcilikField;
            }
            set
            {
                this.disTemsilcilikField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string YabanciAdres
        {
            get
            {
                return this.yabanciAdresField;
            }
            set
            {
                this.yabanciAdresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string YabanciSehir
        {
            get
            {
                return this.yabanciSehirField;
            }
            set
            {
                this.yabanciSehirField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Parametre YabanciUlke
        {
            get
            {
                return this.yabanciUlkeField;
            }
            set
            {
                this.yabanciUlkeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExtensionDataObject
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Parametre
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string aciklamaField;
        
        private System.Nullable<int> kodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Aciklama
        {
            get
            {
                return this.aciklamaField;
            }
            set
            {
                this.aciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> Kod
        {
            get
            {
                return this.kodField;
            }
            set
            {
                this.kodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KimlikNoileKoyAdresi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private Parametre bagimsizBolumDurumField;
        
        private Parametre bagimsizBolumTipiField;
        
        private string binaAdaField;
        
        private string binaBlokAdiField;
        
        private Parametre binaDurumField;
        
        private System.Nullable<long> binaKoduField;
        
        private System.Nullable<int> binaNoField;
        
        private Parametre binaNumaratajTipiField;
        
        private string binaPaftaField;
        
        private string binaParselField;
        
        private string binaSiteAdiField;
        
        private Parametre binaYapiTipiField;
        
        private string csbmField;
        
        private System.Nullable<int> csbmKoduField;
        
        private string disKapiNoField;
        
        private Parametre hataBilgisiField;
        
        private string icKapiNoField;
        
        private string ilField;
        
        private System.Nullable<int> ilKoduField;
        
        private string ilceField;
        
        private System.Nullable<int> ilceKoduField;
        
        private string katNoField;
        
        private string koyField;
        
        private System.Nullable<long> koyKayitNoField;
        
        private System.Nullable<long> koyKoduField;
        
        private string mahalleField;
        
        private System.Nullable<int> mahalleKoduField;
        
        private string tapuBagimsizBolumNoField;
        
        private Parametre yapiKullanimAmacField;
        
        private System.Nullable<int> yolAltiKatSayisiField;
        
        private System.Nullable<int> yolUstuKatSayisiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Parametre BagimsizBolumDurum
        {
            get
            {
                return this.bagimsizBolumDurumField;
            }
            set
            {
                this.bagimsizBolumDurumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Parametre BagimsizBolumTipi
        {
            get
            {
                return this.bagimsizBolumTipiField;
            }
            set
            {
                this.bagimsizBolumTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BinaAda
        {
            get
            {
                return this.binaAdaField;
            }
            set
            {
                this.binaAdaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BinaBlokAdi
        {
            get
            {
                return this.binaBlokAdiField;
            }
            set
            {
                this.binaBlokAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Parametre BinaDurum
        {
            get
            {
                return this.binaDurumField;
            }
            set
            {
                this.binaDurumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<long> BinaKodu
        {
            get
            {
                return this.binaKoduField;
            }
            set
            {
                this.binaKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> BinaNo
        {
            get
            {
                return this.binaNoField;
            }
            set
            {
                this.binaNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Parametre BinaNumaratajTipi
        {
            get
            {
                return this.binaNumaratajTipiField;
            }
            set
            {
                this.binaNumaratajTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string BinaPafta
        {
            get
            {
                return this.binaPaftaField;
            }
            set
            {
                this.binaPaftaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string BinaParsel
        {
            get
            {
                return this.binaParselField;
            }
            set
            {
                this.binaParselField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string BinaSiteAdi
        {
            get
            {
                return this.binaSiteAdiField;
            }
            set
            {
                this.binaSiteAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public Parametre BinaYapiTipi
        {
            get
            {
                return this.binaYapiTipiField;
            }
            set
            {
                this.binaYapiTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Csbm
        {
            get
            {
                return this.csbmField;
            }
            set
            {
                this.csbmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> CsbmKodu
        {
            get
            {
                return this.csbmKoduField;
            }
            set
            {
                this.csbmKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string DisKapiNo
        {
            get
            {
                return this.disKapiNoField;
            }
            set
            {
                this.disKapiNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string IcKapiNo
        {
            get
            {
                return this.icKapiNoField;
            }
            set
            {
                this.icKapiNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Il
        {
            get
            {
                return this.ilField;
            }
            set
            {
                this.ilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<int> IlKodu
        {
            get
            {
                return this.ilKoduField;
            }
            set
            {
                this.ilKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Ilce
        {
            get
            {
                return this.ilceField;
            }
            set
            {
                this.ilceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<int> IlceKodu
        {
            get
            {
                return this.ilceKoduField;
            }
            set
            {
                this.ilceKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string KatNo
        {
            get
            {
                return this.katNoField;
            }
            set
            {
                this.katNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Koy
        {
            get
            {
                return this.koyField;
            }
            set
            {
                this.koyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<long> KoyKayitNo
        {
            get
            {
                return this.koyKayitNoField;
            }
            set
            {
                this.koyKayitNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<long> KoyKodu
        {
            get
            {
                return this.koyKoduField;
            }
            set
            {
                this.koyKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Mahalle
        {
            get
            {
                return this.mahalleField;
            }
            set
            {
                this.mahalleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public System.Nullable<int> MahalleKodu
        {
            get
            {
                return this.mahalleKoduField;
            }
            set
            {
                this.mahalleKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string TapuBagimsizBolumNo
        {
            get
            {
                return this.tapuBagimsizBolumNoField;
            }
            set
            {
                this.tapuBagimsizBolumNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public Parametre YapiKullanimAmac
        {
            get
            {
                return this.yapiKullanimAmacField;
            }
            set
            {
                this.yapiKullanimAmacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public System.Nullable<int> YolAltiKatSayisi
        {
            get
            {
                return this.yolAltiKatSayisiField;
            }
            set
            {
                this.yolAltiKatSayisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public System.Nullable<int> YolUstuKatSayisi
        {
            get
            {
                return this.yolUstuKatSayisiField;
            }
            set
            {
                this.yolUstuKatSayisiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KimlikNoileIlIlceMerkezi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private Parametre bagimsizBolumDurumField;
        
        private Parametre bagimsizBolumTipiField;
        
        private string binaAdaField;
        
        private string binaBlokAdiField;
        
        private Parametre binaDurumField;
        
        private System.Nullable<long> binaKoduField;
        
        private System.Nullable<int> binaNoField;
        
        private Parametre binaNumaratajTipiField;
        
        private string binaPaftaField;
        
        private string binaParselField;
        
        private string binaSiteAdiField;
        
        private Parametre binaYapiTipiField;
        
        private string csbmField;
        
        private System.Nullable<int> csbmKoduField;
        
        private string disKapiNoField;
        
        private Parametre hataBilgisiField;
        
        private string icKapiNoField;
        
        private string ilField;
        
        private System.Nullable<int> ilKoduField;
        
        private string ilceField;
        
        private System.Nullable<int> ilceKoduField;
        
        private string katNoField;
        
        private string mahalleField;
        
        private System.Nullable<int> mahalleKoduField;
        
        private string tapuBagimsizBolumNoField;
        
        private Parametre yapiKullanimAmacField;
        
        private System.Nullable<int> yolAltiKatSayisiField;
        
        private System.Nullable<int> yolUstuKatSayisiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Parametre BagimsizBolumDurum
        {
            get
            {
                return this.bagimsizBolumDurumField;
            }
            set
            {
                this.bagimsizBolumDurumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Parametre BagimsizBolumTipi
        {
            get
            {
                return this.bagimsizBolumTipiField;
            }
            set
            {
                this.bagimsizBolumTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BinaAda
        {
            get
            {
                return this.binaAdaField;
            }
            set
            {
                this.binaAdaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BinaBlokAdi
        {
            get
            {
                return this.binaBlokAdiField;
            }
            set
            {
                this.binaBlokAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Parametre BinaDurum
        {
            get
            {
                return this.binaDurumField;
            }
            set
            {
                this.binaDurumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<long> BinaKodu
        {
            get
            {
                return this.binaKoduField;
            }
            set
            {
                this.binaKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> BinaNo
        {
            get
            {
                return this.binaNoField;
            }
            set
            {
                this.binaNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Parametre BinaNumaratajTipi
        {
            get
            {
                return this.binaNumaratajTipiField;
            }
            set
            {
                this.binaNumaratajTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string BinaPafta
        {
            get
            {
                return this.binaPaftaField;
            }
            set
            {
                this.binaPaftaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string BinaParsel
        {
            get
            {
                return this.binaParselField;
            }
            set
            {
                this.binaParselField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string BinaSiteAdi
        {
            get
            {
                return this.binaSiteAdiField;
            }
            set
            {
                this.binaSiteAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public Parametre BinaYapiTipi
        {
            get
            {
                return this.binaYapiTipiField;
            }
            set
            {
                this.binaYapiTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Csbm
        {
            get
            {
                return this.csbmField;
            }
            set
            {
                this.csbmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> CsbmKodu
        {
            get
            {
                return this.csbmKoduField;
            }
            set
            {
                this.csbmKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string DisKapiNo
        {
            get
            {
                return this.disKapiNoField;
            }
            set
            {
                this.disKapiNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string IcKapiNo
        {
            get
            {
                return this.icKapiNoField;
            }
            set
            {
                this.icKapiNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Il
        {
            get
            {
                return this.ilField;
            }
            set
            {
                this.ilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<int> IlKodu
        {
            get
            {
                return this.ilKoduField;
            }
            set
            {
                this.ilKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Ilce
        {
            get
            {
                return this.ilceField;
            }
            set
            {
                this.ilceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<int> IlceKodu
        {
            get
            {
                return this.ilceKoduField;
            }
            set
            {
                this.ilceKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string KatNo
        {
            get
            {
                return this.katNoField;
            }
            set
            {
                this.katNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Mahalle
        {
            get
            {
                return this.mahalleField;
            }
            set
            {
                this.mahalleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<int> MahalleKodu
        {
            get
            {
                return this.mahalleKoduField;
            }
            set
            {
                this.mahalleKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string TapuBagimsizBolumNo
        {
            get
            {
                return this.tapuBagimsizBolumNoField;
            }
            set
            {
                this.tapuBagimsizBolumNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public Parametre YapiKullanimAmac
        {
            get
            {
                return this.yapiKullanimAmacField;
            }
            set
            {
                this.yapiKullanimAmacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public System.Nullable<int> YolAltiKatSayisi
        {
            get
            {
                return this.yolAltiKatSayisiField;
            }
            set
            {
                this.yolAltiKatSayisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public System.Nullable<int> YolUstuKatSayisi
        {
            get
            {
                return this.yolUstuKatSayisiField;
            }
            set
            {
                this.yolUstuKatSayisiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TarihBilgisi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> ayField;
        
        private System.Nullable<int> gunField;
        
        private System.Nullable<int> yilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> Ay
        {
            get
            {
                return this.ayField;
            }
            set
            {
                this.ayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> Gun
        {
            get
            {
                return this.gunField;
            }
            set
            {
                this.gunField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> Yil
        {
            get
            {
                return this.yilField;
            }
            set
            {
                this.yilField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KimlikNoileBeldeAdresi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private Parametre bagimsizBolumDurumField;
        
        private Parametre bagimsizBolumTipiField;
        
        private string binaAdaField;
        
        private string binaBlokAdiField;
        
        private Parametre binaDurumField;
        
        private System.Nullable<long> binaKoduField;
        
        private System.Nullable<int> binaNoField;
        
        private Parametre binaNumaratajTipiField;
        
        private string binaPaftaField;
        
        private string binaParselField;
        
        private string binaSiteAdiField;
        
        private Parametre binaYapiTipiField;
        
        private string csbmField;
        
        private System.Nullable<int> csbmKoduField;
        
        private string disKapiNoField;
        
        private Parametre hataBilgisiField;
        
        private string icKapiNoField;
        
        private string ilField;
        
        private System.Nullable<int> ilKoduField;
        
        private string ilceField;
        
        private System.Nullable<int> ilceKoduField;
        
        private string katNoField;
        
        private string koyField;
        
        private System.Nullable<long> koyKayitNoField;
        
        private System.Nullable<long> koyKoduField;
        
        private string mahalleField;
        
        private System.Nullable<int> mahalleKoduField;
        
        private string tapuBagimsizBolumNoField;
        
        private Parametre yapiKullanimAmacField;
        
        private System.Nullable<int> yolAltiKatSayisiField;
        
        private System.Nullable<int> yolUstuKatSayisiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Parametre BagimsizBolumDurum
        {
            get
            {
                return this.bagimsizBolumDurumField;
            }
            set
            {
                this.bagimsizBolumDurumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Parametre BagimsizBolumTipi
        {
            get
            {
                return this.bagimsizBolumTipiField;
            }
            set
            {
                this.bagimsizBolumTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BinaAda
        {
            get
            {
                return this.binaAdaField;
            }
            set
            {
                this.binaAdaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BinaBlokAdi
        {
            get
            {
                return this.binaBlokAdiField;
            }
            set
            {
                this.binaBlokAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Parametre BinaDurum
        {
            get
            {
                return this.binaDurumField;
            }
            set
            {
                this.binaDurumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<long> BinaKodu
        {
            get
            {
                return this.binaKoduField;
            }
            set
            {
                this.binaKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> BinaNo
        {
            get
            {
                return this.binaNoField;
            }
            set
            {
                this.binaNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Parametre BinaNumaratajTipi
        {
            get
            {
                return this.binaNumaratajTipiField;
            }
            set
            {
                this.binaNumaratajTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string BinaPafta
        {
            get
            {
                return this.binaPaftaField;
            }
            set
            {
                this.binaPaftaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string BinaParsel
        {
            get
            {
                return this.binaParselField;
            }
            set
            {
                this.binaParselField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string BinaSiteAdi
        {
            get
            {
                return this.binaSiteAdiField;
            }
            set
            {
                this.binaSiteAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public Parametre BinaYapiTipi
        {
            get
            {
                return this.binaYapiTipiField;
            }
            set
            {
                this.binaYapiTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Csbm
        {
            get
            {
                return this.csbmField;
            }
            set
            {
                this.csbmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> CsbmKodu
        {
            get
            {
                return this.csbmKoduField;
            }
            set
            {
                this.csbmKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string DisKapiNo
        {
            get
            {
                return this.disKapiNoField;
            }
            set
            {
                this.disKapiNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string IcKapiNo
        {
            get
            {
                return this.icKapiNoField;
            }
            set
            {
                this.icKapiNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Il
        {
            get
            {
                return this.ilField;
            }
            set
            {
                this.ilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<int> IlKodu
        {
            get
            {
                return this.ilKoduField;
            }
            set
            {
                this.ilKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Ilce
        {
            get
            {
                return this.ilceField;
            }
            set
            {
                this.ilceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<int> IlceKodu
        {
            get
            {
                return this.ilceKoduField;
            }
            set
            {
                this.ilceKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string KatNo
        {
            get
            {
                return this.katNoField;
            }
            set
            {
                this.katNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Koy
        {
            get
            {
                return this.koyField;
            }
            set
            {
                this.koyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<long> KoyKayitNo
        {
            get
            {
                return this.koyKayitNoField;
            }
            set
            {
                this.koyKayitNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<long> KoyKodu
        {
            get
            {
                return this.koyKoduField;
            }
            set
            {
                this.koyKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Mahalle
        {
            get
            {
                return this.mahalleField;
            }
            set
            {
                this.mahalleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public System.Nullable<int> MahalleKodu
        {
            get
            {
                return this.mahalleKoduField;
            }
            set
            {
                this.mahalleKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string TapuBagimsizBolumNo
        {
            get
            {
                return this.tapuBagimsizBolumNoField;
            }
            set
            {
                this.tapuBagimsizBolumNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public Parametre YapiKullanimAmac
        {
            get
            {
                return this.yapiKullanimAmacField;
            }
            set
            {
                this.yapiKullanimAmacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public System.Nullable<int> YolAltiKatSayisi
        {
            get
            {
                return this.yolAltiKatSayisiField;
            }
            set
            {
                this.yolAltiKatSayisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public System.Nullable<int> YolUstuKatSayisi
        {
            get
            {
                return this.yolUstuKatSayisiField;
            }
            set
            {
                this.yolUstuKatSayisiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KimlikNoileKisiAdresBilgisi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string acikAdresField;
        
        private System.Nullable<long> adresNoField;
        
        private Parametre adresTipField;
        
        private KimlikNoileBeldeAdresi beldeAdresiField;
        
        private TarihBilgisi beyanTarihiField;
        
        private System.Nullable<long> beyandaBulunanKimlikNoField;
        
        private Parametre hataBilgisiField;
        
        private KimlikNoileIlIlceMerkezi ilIlceMerkezAdresiField;
        
        private KimlikNoileKoyAdresi koyAdresiField;
        
        private Parametre tasinmaNedenField;
        
        private TarihBilgisi tasinmaTarihiField;
        
        private TarihBilgisi tescilTarihiField;
        
        private KimlikNoileYurtDisiAdresi yurtDisiAdresiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AcikAdres
        {
            get
            {
                return this.acikAdresField;
            }
            set
            {
                this.acikAdresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> AdresNo
        {
            get
            {
                return this.adresNoField;
            }
            set
            {
                this.adresNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Parametre AdresTip
        {
            get
            {
                return this.adresTipField;
            }
            set
            {
                this.adresTipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public KimlikNoileBeldeAdresi BeldeAdresi
        {
            get
            {
                return this.beldeAdresiField;
            }
            set
            {
                this.beldeAdresiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public TarihBilgisi BeyanTarihi
        {
            get
            {
                return this.beyanTarihiField;
            }
            set
            {
                this.beyanTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<long> BeyandaBulunanKimlikNo
        {
            get
            {
                return this.beyandaBulunanKimlikNoField;
            }
            set
            {
                this.beyandaBulunanKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public KimlikNoileIlIlceMerkezi IlIlceMerkezAdresi
        {
            get
            {
                return this.ilIlceMerkezAdresiField;
            }
            set
            {
                this.ilIlceMerkezAdresiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public KimlikNoileKoyAdresi KoyAdresi
        {
            get
            {
                return this.koyAdresiField;
            }
            set
            {
                this.koyAdresiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public Parametre TasinmaNeden
        {
            get
            {
                return this.tasinmaNedenField;
            }
            set
            {
                this.tasinmaNedenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public TarihBilgisi TasinmaTarihi
        {
            get
            {
                return this.tasinmaTarihiField;
            }
            set
            {
                this.tasinmaTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public TarihBilgisi TescilTarihi
        {
            get
            {
                return this.tescilTarihiField;
            }
            set
            {
                this.tescilTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public KimlikNoileYurtDisiAdresi YurtDisiAdresi
        {
            get
            {
                return this.yurtDisiAdresiField;
            }
            set
            {
                this.yurtDisiAdresiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KimlikNoileKisiAdresBilgileri
    {
        
        private ExtensionDataObject extensionDataField;
        
        private KimlikNoileKisiAdresBilgisi[] digerAdresBilgileriField;
        
        private Parametre hataBilgisiField;
        
        private System.Nullable<long> kimlikNoField;
        
        private KimlikNoileKisiAdresBilgisi yerlesimYeriAdresiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public KimlikNoileKisiAdresBilgisi[] DigerAdresBilgileri
        {
            get
            {
                return this.digerAdresBilgileriField;
            }
            set
            {
                this.digerAdresBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<long> KimlikNo
        {
            get
            {
                return this.kimlikNoField;
            }
            set
            {
                this.kimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public KimlikNoileKisiAdresBilgisi YerlesimYeriAdresi
        {
            get
            {
                return this.yerlesimYeriAdresiField;
            }
            set
            {
                this.yerlesimYeriAdresiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KimlikNoileKisiAdresBilgileriSonucu
    {
        
        private ExtensionDataObject extensionDataField;
        
        private Parametre hataBilgisiField;
        
        private KimlikNoileKisiAdresBilgileri[] sorguSonucuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public KimlikNoileKisiAdresBilgileri[] SorguSonucu
        {
            get
            {
                return this.sorguSonucuField;
            }
            set
            {
                this.sorguSonucuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KimlikNoileAdresSorguKriteri
    {
        
        private ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> kimlikNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<long> KimlikNo
        {
            get
            {
                return this.kimlikNoField;
            }
            set
            {
                this.kimlikNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sorgula", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SorgulaRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public MernisAdres.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MernisAdres.KimlikNoileAdresSorguKriteri[] Kriter;
        
        public SorgulaRequest()
        {
        }
        
        public SorgulaRequest(MernisAdres.AuthHeader AuthHeader, MernisAdres.KimlikNoileAdresSorguKriteri[] Kriter)
        {
            this.AuthHeader = AuthHeader;
            this.Kriter = Kriter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SorgulaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SorgulaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MernisAdres.KimlikNoileKisiAdresBilgileriSonucu SorgulaResult;
        
        public SorgulaResponse()
        {
        }
        
        public SorgulaResponse(MernisAdres.KimlikNoileKisiAdresBilgileriSonucu SorgulaResult)
        {
            this.SorgulaResult = SorgulaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SorgulaMP", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SorgulaMPRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MernisAdres.KimlikNoileAdresSorguKriteri[] Kriter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string uName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string SorgulayanKullanici;
        
        public SorgulaMPRequest()
        {
        }
        
        public SorgulaMPRequest(MernisAdres.KimlikNoileAdresSorguKriteri[] Kriter, string uName, string pwd, string sessionID, string SorgulayanKullanici)
        {
            this.Kriter = Kriter;
            this.uName = uName;
            this.pwd = pwd;
            this.sessionID = sessionID;
            this.SorgulayanKullanici = SorgulayanKullanici;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SorgulaMPResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SorgulaMPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MernisAdres.KimlikNoileKisiAdresBilgileriSonucu SorgulaMPResult;
        
        public SorgulaMPResponse()
        {
        }
        
        public SorgulaMPResponse(MernisAdres.KimlikNoileKisiAdresBilgileriSonucu SorgulaMPResult)
        {
            this.SorgulaMPResult = SorgulaMPResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface TcKimlikNoSorgulaAdresServisSoapChannel : MernisAdres.TcKimlikNoSorgulaAdresServisSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class TcKimlikNoSorgulaAdresServisSoapClient : System.ServiceModel.ClientBase<MernisAdres.TcKimlikNoSorgulaAdresServisSoap>, MernisAdres.TcKimlikNoSorgulaAdresServisSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TcKimlikNoSorgulaAdresServisSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(TcKimlikNoSorgulaAdresServisSoapClient.GetBindingForEndpoint(endpointConfiguration), TcKimlikNoSorgulaAdresServisSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TcKimlikNoSorgulaAdresServisSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TcKimlikNoSorgulaAdresServisSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TcKimlikNoSorgulaAdresServisSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TcKimlikNoSorgulaAdresServisSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TcKimlikNoSorgulaAdresServisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public MernisAdres.SorgulaResponse Sorgula(MernisAdres.SorgulaRequest request)
        {
            return base.Channel.Sorgula(request);
        }
        
        public System.Threading.Tasks.Task<MernisAdres.SorgulaResponse> SorgulaAsync(MernisAdres.SorgulaRequest request)
        {
            return base.Channel.SorgulaAsync(request);
        }
        
        public MernisAdres.SorgulaMPResponse SorgulaMP(MernisAdres.SorgulaMPRequest request)
        {
            return base.Channel.SorgulaMP(request);
        }
        
        public System.Threading.Tasks.Task<MernisAdres.SorgulaMPResponse> SorgulaMPAsync(MernisAdres.SorgulaMPRequest request)
        {
            return base.Channel.SorgulaMPAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TcKimlikNoSorgulaAdresServisSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TcKimlikNoSorgulaAdresServisSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TcKimlikNoSorgulaAdresServisSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://wsint130.ailevecalisma.gov.tr:8001/TcKimlikNoSorgulaAdresServis.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.TcKimlikNoSorgulaAdresServisSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://wsint130.ailevecalisma.gov.tr:8001/TcKimlikNoSorgulaAdresServis.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            TcKimlikNoSorgulaAdresServisSoap,
            
            TcKimlikNoSorgulaAdresServisSoap12,
        }
    }
}
