//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSYMWsintra
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wsintra.ailevecalisma.gov.tr/osym/sinav", ConfigurationName="OSYMWsintra.ISinavService")]
    public interface ISinavService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsintra.ailevecalisma.gov.tr/osym/sinav/ISinavService/SinavGrupBilgilerini" +
            "Getir", ReplyAction="http://wsintra.ailevecalisma.gov.tr/osym/sinav/ISinavService/SinavGrupBilgilerini" +
            "GetirResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServisSonuc))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResponseBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RequestBase))]
        OSYMWsintra.SinavGrupBilgileriniGetirResp SinavGrupBilgileriniGetir(OSYMWsintra.SinavGrupBilgileriniGetirReq request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsintra.ailevecalisma.gov.tr/osym/sinav/ISinavService/SinavGrupBilgilerini" +
            "Getir", ReplyAction="http://wsintra.ailevecalisma.gov.tr/osym/sinav/ISinavService/SinavGrupBilgilerini" +
            "GetirResponse")]
        System.Threading.Tasks.Task<OSYMWsintra.SinavGrupBilgileriniGetirResp> SinavGrupBilgileriniGetirAsync(OSYMWsintra.SinavGrupBilgileriniGetirReq request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsintra.ailevecalisma.gov.tr/osym/sinav/ISinavService/SinavSonucHtml", ReplyAction="http://wsintra.ailevecalisma.gov.tr/osym/sinav/ISinavService/SinavSonucHtmlRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServisSonuc))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResponseBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RequestBase))]
        OSYMWsintra.SinavSonucHtmlResp SinavSonucHtml(OSYMWsintra.SinavSonucHtmlReq request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsintra.ailevecalisma.gov.tr/osym/sinav/ISinavService/SinavSonucHtml", ReplyAction="http://wsintra.ailevecalisma.gov.tr/osym/sinav/ISinavService/SinavSonucHtmlRespon" +
            "se")]
        System.Threading.Tasks.Task<OSYMWsintra.SinavSonucHtmlResp> SinavSonucHtmlAsync(OSYMWsintra.SinavSonucHtmlReq request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsintra.ailevecalisma.gov.tr/osym/sinav/ISinavService/SinavSonuclariGetir", ReplyAction="http://wsintra.ailevecalisma.gov.tr/osym/sinav/ISinavService/SinavSonuclariGetirR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServisSonuc))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResponseBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RequestBase))]
        OSYMWsintra.SinavSonuclariGetirResp SinavSonuclariGetir(OSYMWsintra.SinavSonuclariGetirReq request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsintra.ailevecalisma.gov.tr/osym/sinav/ISinavService/SinavSonuclariGetir", ReplyAction="http://wsintra.ailevecalisma.gov.tr/osym/sinav/ISinavService/SinavSonuclariGetirR" +
            "esponse")]
        System.Threading.Tasks.Task<OSYMWsintra.SinavSonuclariGetirResp> SinavSonuclariGetirAsync(OSYMWsintra.SinavSonuclariGetirReq request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsintra.ailevecalisma.gov.tr/osym/sinav/ISinavService/SinavSonucXml", ReplyAction="http://wsintra.ailevecalisma.gov.tr/osym/sinav/ISinavService/SinavSonucXmlRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServisSonuc))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResponseBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RequestBase))]
        OSYMWsintra.SinavSonucXmlResp SinavSonucXml(OSYMWsintra.SinavSonucXmlReq request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsintra.ailevecalisma.gov.tr/osym/sinav/ISinavService/SinavSonucXml", ReplyAction="http://wsintra.ailevecalisma.gov.tr/osym/sinav/ISinavService/SinavSonucXmlRespons" +
            "e")]
        System.Threading.Tasks.Task<OSYMWsintra.SinavSonucXmlResp> SinavSonucXmlAsync(OSYMWsintra.SinavSonucXmlReq request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsintra.ailevecalisma.gov.tr/osym/sinav")]
    public partial class SinavGrupBilgileriniGetirReq : RequestBase
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SinavSonucXmlReq))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SinavSonuclariGetirReq))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SinavSonucHtmlReq))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SinavGrupBilgileriniGetirReq))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsintra.ailevecalisma.gov.tr/osym/sinav")]
    public abstract partial class RequestBase
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsintra.ailevecalisma.gov.tr/osym/sinav")]
    public partial class SonucBilgiXml
    {
        
        private ExtensionDataObject extensionDataField;
        
        private System.DateTime aciklamaTarihiField;
        
        private string sonucAdField;
        
        private string xmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime AciklamaTarihi
        {
            get
            {
                return this.aciklamaTarihiField;
            }
            set
            {
                this.aciklamaTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SonucAd
        {
            get
            {
                return this.sonucAdField;
            }
            set
            {
                this.sonucAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsintra.ailevecalisma.gov.tr/osym/sinav")]
    public partial class ExtensionDataObject
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsintra.ailevecalisma.gov.tr/osym/sinav")]
    public partial class SinavSonucTemelBilgi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private System.DateTime aciklamaTarihiField;
        
        private string adField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime AciklamaTarihi
        {
            get
            {
                return this.aciklamaTarihiField;
            }
            set
            {
                this.aciklamaTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Ad
        {
            get
            {
                return this.adField;
            }
            set
            {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsintra.ailevecalisma.gov.tr/osym/sinav")]
    public partial class SonucBilgiHtml
    {
        
        private ExtensionDataObject extensionDataField;
        
        private System.DateTime aciklamaTarihiField;
        
        private string sonucAdField;
        
        private byte[] sonucHtmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime AciklamaTarihi
        {
            get
            {
                return this.aciklamaTarihiField;
            }
            set
            {
                this.aciklamaTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SonucAd
        {
            get
            {
                return this.sonucAdField;
            }
            set
            {
                this.sonucAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] SonucHtml
        {
            get
            {
                return this.sonucHtmlField;
            }
            set
            {
                this.sonucHtmlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsintra.ailevecalisma.gov.tr/osym/sinav")]
    public partial class SinavGrupBilgi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string adField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ad
        {
            get
            {
                return this.adField;
            }
            set
            {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServisSonucOfSonucBilgiXmlYKHEH_S_P5))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServisSonucOfArrayOfSinavSonucTemelBilgiYKHEH_S_P5))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServisSonucOfSonucBilgiHtmlYKHEH_S_P5))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServisSonucOfArrayOfSinavGrupBilgiYKHEH_S_P5))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsintra.ailevecalisma.gov.tr/osym/sinav")]
    public partial class ServisSonuc
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string aciklamaField;
        
        private SonucKodu sonucKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Aciklama
        {
            get
            {
                return this.aciklamaField;
            }
            set
            {
                this.aciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SonucKodu SonucKodu
        {
            get
            {
                return this.sonucKoduField;
            }
            set
            {
                this.sonucKoduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsintra.ailevecalisma.gov.tr/osym/sinav")]
    public enum SonucKodu
    {
        
        /// <remarks/>
        KayitBulunamadi,
        
        /// <remarks/>
        Basarili,
        
        /// <remarks/>
        GecersizVeri,
        
        /// <remarks/>
        YetkisizIslem,
        
        /// <remarks/>
        ZamanAsimi,
        
        /// <remarks/>
        BeklenmeyenHata,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsintra.ailevecalisma.gov.tr/osym/sinav")]
    public partial class ServisSonucOfSonucBilgiXmlYKHEH_S_P5 : ServisSonuc
    {
        
        private SonucBilgiXml sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SonucBilgiXml Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsintra.ailevecalisma.gov.tr/osym/sinav")]
    public partial class ServisSonucOfArrayOfSinavSonucTemelBilgiYKHEH_S_P5 : ServisSonuc
    {
        
        private SinavSonucTemelBilgi[] sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public SinavSonucTemelBilgi[] Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsintra.ailevecalisma.gov.tr/osym/sinav")]
    public partial class ServisSonucOfSonucBilgiHtmlYKHEH_S_P5 : ServisSonuc
    {
        
        private SonucBilgiHtml sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SonucBilgiHtml Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsintra.ailevecalisma.gov.tr/osym/sinav")]
    public partial class ServisSonucOfArrayOfSinavGrupBilgiYKHEH_S_P5 : ServisSonuc
    {
        
        private SinavGrupBilgi[] sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public SinavGrupBilgi[] Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsintra.ailevecalisma.gov.tr/osym/sinav")]
    public partial class ResultErrorInfo
    {
        
        private string hataKoduField;
        
        private string hataMesajiField;
        
        private string hataLogIDField;
        
        private string sistemHataMesajiField;
        
        private string kullaniciHataMesajiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string HataKodu
        {
            get
            {
                return this.hataKoduField;
            }
            set
            {
                this.hataKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string HataMesaji
        {
            get
            {
                return this.hataMesajiField;
            }
            set
            {
                this.hataMesajiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string HataLogID
        {
            get
            {
                return this.hataLogIDField;
            }
            set
            {
                this.hataLogIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SistemHataMesaji
        {
            get
            {
                return this.sistemHataMesajiField;
            }
            set
            {
                this.sistemHataMesajiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string KullaniciHataMesaji
        {
            get
            {
                return this.kullaniciHataMesajiField;
            }
            set
            {
                this.kullaniciHataMesajiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SinavSonucXmlResp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SinavSonuclariGetirResp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SinavSonucHtmlResp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SinavGrupBilgileriniGetirResp))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsintra.ailevecalisma.gov.tr/osym/sinav")]
    public partial class ResponseBase
    {
        
        private ResultErrorInfo sorguHataDurumuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResultErrorInfo SorguHataDurumu
        {
            get
            {
                return this.sorguHataDurumuField;
            }
            set
            {
                this.sorguHataDurumuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsintra.ailevecalisma.gov.tr/osym/sinav")]
    public partial class SinavSonucXmlResp : ResponseBase
    {
        
        private ServisSonucOfSonucBilgiXmlYKHEH_S_P5 sorguSonucuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ServisSonucOfSonucBilgiXmlYKHEH_S_P5 SorguSonucu
        {
            get
            {
                return this.sorguSonucuField;
            }
            set
            {
                this.sorguSonucuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsintra.ailevecalisma.gov.tr/osym/sinav")]
    public partial class SinavSonuclariGetirResp : ResponseBase
    {
        
        private ServisSonucOfArrayOfSinavSonucTemelBilgiYKHEH_S_P5 sorguSonucuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ServisSonucOfArrayOfSinavSonucTemelBilgiYKHEH_S_P5 SorguSonucu
        {
            get
            {
                return this.sorguSonucuField;
            }
            set
            {
                this.sorguSonucuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsintra.ailevecalisma.gov.tr/osym/sinav")]
    public partial class SinavSonucHtmlResp : ResponseBase
    {
        
        private ServisSonucOfSonucBilgiHtmlYKHEH_S_P5 sorguSonucuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ServisSonucOfSonucBilgiHtmlYKHEH_S_P5 SorguSonucu
        {
            get
            {
                return this.sorguSonucuField;
            }
            set
            {
                this.sorguSonucuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsintra.ailevecalisma.gov.tr/osym/sinav")]
    public partial class SinavGrupBilgileriniGetirResp : ResponseBase
    {
        
        private ServisSonucOfArrayOfSinavGrupBilgiYKHEH_S_P5 sorguSonucuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ServisSonucOfArrayOfSinavGrupBilgiYKHEH_S_P5 SorguSonucu
        {
            get
            {
                return this.sorguSonucuField;
            }
            set
            {
                this.sorguSonucuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsintra.ailevecalisma.gov.tr/osym/sinav")]
    public partial class SinavSonucXmlReq : RequestBase
    {
        
        private string adayTcKimlikNoField;
        
        private int sonucIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string adayTcKimlikNo
        {
            get
            {
                return this.adayTcKimlikNoField;
            }
            set
            {
                this.adayTcKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int sonucId
        {
            get
            {
                return this.sonucIdField;
            }
            set
            {
                this.sonucIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsintra.ailevecalisma.gov.tr/osym/sinav")]
    public partial class SinavSonuclariGetirReq : RequestBase
    {
        
        private string adayTcKimlikNoField;
        
        private int yilField;
        
        private int sinavGrupIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string adayTcKimlikNo
        {
            get
            {
                return this.adayTcKimlikNoField;
            }
            set
            {
                this.adayTcKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int yil
        {
            get
            {
                return this.yilField;
            }
            set
            {
                this.yilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int sinavGrupId
        {
            get
            {
                return this.sinavGrupIdField;
            }
            set
            {
                this.sinavGrupIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsintra.ailevecalisma.gov.tr/osym/sinav")]
    public partial class SinavSonucHtmlReq : RequestBase
    {
        
        private string adayTcKimlikNoField;
        
        private int sonucIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string adayTcKimlikNo
        {
            get
            {
                return this.adayTcKimlikNoField;
            }
            set
            {
                this.adayTcKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int sonucId
        {
            get
            {
                return this.sonucIdField;
            }
            set
            {
                this.sonucIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ISinavServiceChannel : OSYMWsintra.ISinavService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SinavServiceClient : System.ServiceModel.ClientBase<OSYMWsintra.ISinavService>, OSYMWsintra.ISinavService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SinavServiceClient() : 
                base(SinavServiceClient.GetDefaultBinding(), SinavServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISinavService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SinavServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SinavServiceClient.GetBindingForEndpoint(endpointConfiguration), SinavServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SinavServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SinavServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SinavServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SinavServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SinavServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public OSYMWsintra.SinavGrupBilgileriniGetirResp SinavGrupBilgileriniGetir(OSYMWsintra.SinavGrupBilgileriniGetirReq request)
        {
            return base.Channel.SinavGrupBilgileriniGetir(request);
        }
        
        public System.Threading.Tasks.Task<OSYMWsintra.SinavGrupBilgileriniGetirResp> SinavGrupBilgileriniGetirAsync(OSYMWsintra.SinavGrupBilgileriniGetirReq request)
        {
            return base.Channel.SinavGrupBilgileriniGetirAsync(request);
        }
        
        public OSYMWsintra.SinavSonucHtmlResp SinavSonucHtml(OSYMWsintra.SinavSonucHtmlReq request)
        {
            return base.Channel.SinavSonucHtml(request);
        }
        
        public System.Threading.Tasks.Task<OSYMWsintra.SinavSonucHtmlResp> SinavSonucHtmlAsync(OSYMWsintra.SinavSonucHtmlReq request)
        {
            return base.Channel.SinavSonucHtmlAsync(request);
        }
        
        public OSYMWsintra.SinavSonuclariGetirResp SinavSonuclariGetir(OSYMWsintra.SinavSonuclariGetirReq request)
        {
            return base.Channel.SinavSonuclariGetir(request);
        }
        
        public System.Threading.Tasks.Task<OSYMWsintra.SinavSonuclariGetirResp> SinavSonuclariGetirAsync(OSYMWsintra.SinavSonuclariGetirReq request)
        {
            return base.Channel.SinavSonuclariGetirAsync(request);
        }
        
        public OSYMWsintra.SinavSonucXmlResp SinavSonucXml(OSYMWsintra.SinavSonucXmlReq request)
        {
            return base.Channel.SinavSonucXml(request);
        }
        
        public System.Threading.Tasks.Task<OSYMWsintra.SinavSonucXmlResp> SinavSonucXmlAsync(OSYMWsintra.SinavSonucXmlReq request)
        {
            return base.Channel.SinavSonucXmlAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISinavService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISinavService))
            {
                return new System.ServiceModel.EndpointAddress("http://wsintra.ailevecalisma.gov.tr/osym/sinav/SinavService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SinavServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISinavService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SinavServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISinavService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISinavService,
        }
    }
}
