//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilesikKutukServis
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/", ConfigurationName="BilesikKutukServis.BilesikKutukSorgulaKimlikNoServiceSoap")]
    public interface BilesikKutukSorgulaKimlikNoServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/BilesikK" +
            "utukSorgulaKimlikNoServis", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BilesikKutukServis.BilesikKutukSorgulaKimlikNoServisResponse> BilesikKutukSorgulaKimlikNoServisAsync(BilesikKutukServis.BilesikKutukSorgulaKimlikNoServisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/BilesikK" +
            "utukSorgulaKimlikNoServisMp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BilesikKutukServis.BilesikKutukBilgileriSonucu> BilesikKutukSorgulaKimlikNoServisMpAsync(BilesikKutukServis.BilesikKutukSorgulaKimlikNoSorguKriteri[] kriterList, string username, string password, string sessionID, string sorgulayanKullanici);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class AuthHeader
    {
        
        private string usernameField;
        
        private string passwordField;
        
        private string sessionIDField;
        
        private string sorgulayanKullaniciField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SessionID
        {
            get
            {
                return this.sessionIDField;
            }
            set
            {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SorgulayanKullanici
        {
            get
            {
                return this.sorgulayanKullaniciField;
            }
            set
            {
                this.sorgulayanKullaniciField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class YabanciKisiTemelBilgisi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string adField;
        
        private string anneAdField;
        
        private string babaAdField;
        
        private Parametre cinsiyetField;
        
        private string dogumYerField;
        
        private string soyadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ad
        {
            get
            {
                return this.adField;
            }
            set
            {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AnneAd
        {
            get
            {
                return this.anneAdField;
            }
            set
            {
                this.anneAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BabaAd
        {
            get
            {
                return this.babaAdField;
            }
            set
            {
                this.babaAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Parametre Cinsiyet
        {
            get
            {
                return this.cinsiyetField;
            }
            set
            {
                this.cinsiyetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DogumYer
        {
            get
            {
                return this.dogumYerField;
            }
            set
            {
                this.dogumYerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Soyad
        {
            get
            {
                return this.soyadField;
            }
            set
            {
                this.soyadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class ExtensionDataObject
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class Parametre
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string aciklamaField;
        
        private System.Nullable<int> kodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Aciklama
        {
            get
            {
                return this.aciklamaField;
            }
            set
            {
                this.aciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> Kod
        {
            get
            {
                return this.kodField;
            }
            set
            {
                this.kodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class YabanciKisiDurumBilgisi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private Parametre durumField;
        
        private Parametre medeniHalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Parametre Durum
        {
            get
            {
                return this.durumField;
            }
            set
            {
                this.durumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Parametre MedeniHal
        {
            get
            {
                return this.medeniHalField;
            }
            set
            {
                this.medeniHalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class YabanciKisiBilgisi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> anneKimlikNoField;
        
        private System.Nullable<long> babaKimlikNoField;
        
        private Parametre bitisTarihiBelirsizOlmaNedenField;
        
        private TarihBilgisi dogumTarihField;
        
        private System.Nullable<int> dogumYerKodField;
        
        private YabanciKisiDurumBilgisi durumBilgisiField;
        
        private System.Nullable<long> esKimlikNoField;
        
        private System.Nullable<long> gercekKisiKimlikNoField;
        
        private Parametre hataBilgisiField;
        
        private System.Nullable<System.DateTime> izinBaslangicTarihField;
        
        private System.Nullable<System.DateTime> izinBitisTarihField;
        
        private Parametre izinDuzenlenenIlField;
        
        private string izinNoField;
        
        private Parametre kaynakBirimField;
        
        private System.Nullable<long> kazanilanTCKimlikNoField;
        
        private System.Nullable<long> kimlikNoField;
        
        private TarihBilgisi olumTarihField;
        
        private YabanciKisiTemelBilgisi temelBilgisiField;
        
        private Parametre uyrukField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<long> AnneKimlikNo
        {
            get
            {
                return this.anneKimlikNoField;
            }
            set
            {
                this.anneKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> BabaKimlikNo
        {
            get
            {
                return this.babaKimlikNoField;
            }
            set
            {
                this.babaKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Parametre BitisTarihiBelirsizOlmaNeden
        {
            get
            {
                return this.bitisTarihiBelirsizOlmaNedenField;
            }
            set
            {
                this.bitisTarihiBelirsizOlmaNedenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TarihBilgisi DogumTarih
        {
            get
            {
                return this.dogumTarihField;
            }
            set
            {
                this.dogumTarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> DogumYerKod
        {
            get
            {
                return this.dogumYerKodField;
            }
            set
            {
                this.dogumYerKodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public YabanciKisiDurumBilgisi DurumBilgisi
        {
            get
            {
                return this.durumBilgisiField;
            }
            set
            {
                this.durumBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<long> EsKimlikNo
        {
            get
            {
                return this.esKimlikNoField;
            }
            set
            {
                this.esKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<long> GercekKisiKimlikNo
        {
            get
            {
                return this.gercekKisiKimlikNoField;
            }
            set
            {
                this.gercekKisiKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<System.DateTime> IzinBaslangicTarih
        {
            get
            {
                return this.izinBaslangicTarihField;
            }
            set
            {
                this.izinBaslangicTarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<System.DateTime> IzinBitisTarih
        {
            get
            {
                return this.izinBitisTarihField;
            }
            set
            {
                this.izinBitisTarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public Parametre IzinDuzenlenenIl
        {
            get
            {
                return this.izinDuzenlenenIlField;
            }
            set
            {
                this.izinDuzenlenenIlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string IzinNo
        {
            get
            {
                return this.izinNoField;
            }
            set
            {
                this.izinNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public Parametre KaynakBirim
        {
            get
            {
                return this.kaynakBirimField;
            }
            set
            {
                this.kaynakBirimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<long> KazanilanTCKimlikNo
        {
            get
            {
                return this.kazanilanTCKimlikNoField;
            }
            set
            {
                this.kazanilanTCKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<long> KimlikNo
        {
            get
            {
                return this.kimlikNoField;
            }
            set
            {
                this.kimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public TarihBilgisi OlumTarih
        {
            get
            {
                return this.olumTarihField;
            }
            set
            {
                this.olumTarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public YabanciKisiTemelBilgisi TemelBilgisi
        {
            get
            {
                return this.temelBilgisiField;
            }
            set
            {
                this.temelBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public Parametre Uyruk
        {
            get
            {
                return this.uyrukField;
            }
            set
            {
                this.uyrukField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class TarihBilgisi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> ayField;
        
        private System.Nullable<int> gunField;
        
        private System.Nullable<int> yilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> Ay
        {
            get
            {
                return this.ayField;
            }
            set
            {
                this.ayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> Gun
        {
            get
            {
                return this.gunField;
            }
            set
            {
                this.gunField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> Yil
        {
            get
            {
                return this.yilField;
            }
            set
            {
                this.yilField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class YabanciKisiKutukleri
    {
        
        private ExtensionDataObject extensionDataField;
        
        private Parametre hataBilgisiField;
        
        private YabanciKisiBilgisi kisiBilgisiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public YabanciKisiBilgisi KisiBilgisi
        {
            get
            {
                return this.kisiBilgisiField;
            }
            set
            {
                this.kisiBilgisiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class TCKKFotoBilgisi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private byte[] fotografField;
        
        private Parametre hataBilgisiField;
        
        private System.Nullable<long> tCKimlikNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] Fotograf
        {
            get
            {
                return this.fotografField;
            }
            set
            {
                this.fotografField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<long> TCKimlikNo
        {
            get
            {
                return this.tCKimlikNoField;
            }
            set
            {
                this.tCKimlikNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class TCKK
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string adField;
        
        private string anneAdField;
        
        private string babaAdField;
        
        private Parametre basvuruNedenField;
        
        private Parametre cinsiyetField;
        
        private TarihBilgisi dogumTarihField;
        
        private string dogumYerField;
        
        private Parametre hataBilgisiField;
        
        private System.Nullable<long> kayitNoField;
        
        private string seriNoField;
        
        private TarihBilgisi sonGecerlilikTarihField;
        
        private string soyadField;
        
        private System.Nullable<long> tCKimlikNoField;
        
        private Parametre teslimEdenBirimField;
        
        private TarihBilgisi teslimTarihField;
        
        private string verenMakamField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ad
        {
            get
            {
                return this.adField;
            }
            set
            {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AnneAd
        {
            get
            {
                return this.anneAdField;
            }
            set
            {
                this.anneAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BabaAd
        {
            get
            {
                return this.babaAdField;
            }
            set
            {
                this.babaAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Parametre BasvuruNeden
        {
            get
            {
                return this.basvuruNedenField;
            }
            set
            {
                this.basvuruNedenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Parametre Cinsiyet
        {
            get
            {
                return this.cinsiyetField;
            }
            set
            {
                this.cinsiyetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public TarihBilgisi DogumTarih
        {
            get
            {
                return this.dogumTarihField;
            }
            set
            {
                this.dogumTarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DogumYer
        {
            get
            {
                return this.dogumYerField;
            }
            set
            {
                this.dogumYerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<long> KayitNo
        {
            get
            {
                return this.kayitNoField;
            }
            set
            {
                this.kayitNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string SeriNo
        {
            get
            {
                return this.seriNoField;
            }
            set
            {
                this.seriNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public TarihBilgisi SonGecerlilikTarih
        {
            get
            {
                return this.sonGecerlilikTarihField;
            }
            set
            {
                this.sonGecerlilikTarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Soyad
        {
            get
            {
                return this.soyadField;
            }
            set
            {
                this.soyadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<long> TCKimlikNo
        {
            get
            {
                return this.tCKimlikNoField;
            }
            set
            {
                this.tCKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public Parametre TeslimEdenBirim
        {
            get
            {
                return this.teslimEdenBirimField;
            }
            set
            {
                this.teslimEdenBirimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public TarihBilgisi TeslimTarih
        {
            get
            {
                return this.teslimTarihField;
            }
            set
            {
                this.teslimTarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string VerenMakam
        {
            get
            {
                return this.verenMakamField;
            }
            set
            {
                this.verenMakamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class TCCuzdanBilgisi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string adField;
        
        private string anneAdField;
        
        private string babaAdField;
        
        private System.Nullable<long> cuzdanKayitNoField;
        
        private Parametre cuzdanVerilmeNedenField;
        
        private TarihBilgisi dogumTarihField;
        
        private string dogumYerField;
        
        private Parametre hataBilgisiField;
        
        private System.Nullable<int> noField;
        
        private string seriField;
        
        private string soyadField;
        
        private System.Nullable<long> tCKimlikNoField;
        
        private Parametre verildigiIlceField;
        
        private TarihBilgisi verilmeTarihField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ad
        {
            get
            {
                return this.adField;
            }
            set
            {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AnneAd
        {
            get
            {
                return this.anneAdField;
            }
            set
            {
                this.anneAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BabaAd
        {
            get
            {
                return this.babaAdField;
            }
            set
            {
                this.babaAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<long> CuzdanKayitNo
        {
            get
            {
                return this.cuzdanKayitNoField;
            }
            set
            {
                this.cuzdanKayitNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Parametre CuzdanVerilmeNeden
        {
            get
            {
                return this.cuzdanVerilmeNedenField;
            }
            set
            {
                this.cuzdanVerilmeNedenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public TarihBilgisi DogumTarih
        {
            get
            {
                return this.dogumTarihField;
            }
            set
            {
                this.dogumTarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DogumYer
        {
            get
            {
                return this.dogumYerField;
            }
            set
            {
                this.dogumYerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> No
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Seri
        {
            get
            {
                return this.seriField;
            }
            set
            {
                this.seriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Soyad
        {
            get
            {
                return this.soyadField;
            }
            set
            {
                this.soyadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<long> TCKimlikNo
        {
            get
            {
                return this.tCKimlikNoField;
            }
            set
            {
                this.tCKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public Parametre VerildigiIlce
        {
            get
            {
                return this.verildigiIlceField;
            }
            set
            {
                this.verildigiIlceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public TarihBilgisi VerilmeTarih
        {
            get
            {
                return this.verilmeTarihField;
            }
            set
            {
                this.verilmeTarihField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class TCKisiTemelBilgisi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string adField;
        
        private string anneAdField;
        
        private string babaAdField;
        
        private Parametre cinsiyetField;
        
        private TarihBilgisi dogumTarihField;
        
        private string dogumYerField;
        
        private string soyadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ad
        {
            get
            {
                return this.adField;
            }
            set
            {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AnneAd
        {
            get
            {
                return this.anneAdField;
            }
            set
            {
                this.anneAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BabaAd
        {
            get
            {
                return this.babaAdField;
            }
            set
            {
                this.babaAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Parametre Cinsiyet
        {
            get
            {
                return this.cinsiyetField;
            }
            set
            {
                this.cinsiyetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public TarihBilgisi DogumTarih
        {
            get
            {
                return this.dogumTarihField;
            }
            set
            {
                this.dogumTarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DogumYer
        {
            get
            {
                return this.dogumYerField;
            }
            set
            {
                this.dogumYerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Soyad
        {
            get
            {
                return this.soyadField;
            }
            set
            {
                this.soyadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class TCKisiKayitYeriBilgisi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> aileSiraNoField;
        
        private System.Nullable<int> bireySiraNoField;
        
        private Parametre ciltField;
        
        private Parametre ilField;
        
        private Parametre ilceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> AileSiraNo
        {
            get
            {
                return this.aileSiraNoField;
            }
            set
            {
                this.aileSiraNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> BireySiraNo
        {
            get
            {
                return this.bireySiraNoField;
            }
            set
            {
                this.bireySiraNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Parametre Cilt
        {
            get
            {
                return this.ciltField;
            }
            set
            {
                this.ciltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Parametre Il
        {
            get
            {
                return this.ilField;
            }
            set
            {
                this.ilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Parametre Ilce
        {
            get
            {
                return this.ilceField;
            }
            set
            {
                this.ilceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class TCKisiDurumBilgisi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private Parametre dinField;
        
        private Parametre durumField;
        
        private Parametre medeniHalField;
        
        private TarihBilgisi olumTarihField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Parametre Din
        {
            get
            {
                return this.dinField;
            }
            set
            {
                this.dinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Parametre Durum
        {
            get
            {
                return this.durumField;
            }
            set
            {
                this.durumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Parametre MedeniHal
        {
            get
            {
                return this.medeniHalField;
            }
            set
            {
                this.medeniHalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TarihBilgisi OlumTarih
        {
            get
            {
                return this.olumTarihField;
            }
            set
            {
                this.olumTarihField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class TCKisiBilgisi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> anneTCKimlikNoField;
        
        private System.Nullable<long> babaTCKimlikNoField;
        
        private System.Nullable<int> dogumYerKodField;
        
        private TCKisiDurumBilgisi durumBilgisiField;
        
        private System.Nullable<long> esTCKimlikNoField;
        
        private Parametre hataBilgisiField;
        
        private TCKisiKayitYeriBilgisi kayitYeriBilgisiField;
        
        private System.Nullable<long> tCKimlikNoField;
        
        private TCKisiTemelBilgisi temelBilgisiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<long> AnneTCKimlikNo
        {
            get
            {
                return this.anneTCKimlikNoField;
            }
            set
            {
                this.anneTCKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> BabaTCKimlikNo
        {
            get
            {
                return this.babaTCKimlikNoField;
            }
            set
            {
                this.babaTCKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> DogumYerKod
        {
            get
            {
                return this.dogumYerKodField;
            }
            set
            {
                this.dogumYerKodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TCKisiDurumBilgisi DurumBilgisi
        {
            get
            {
                return this.durumBilgisiField;
            }
            set
            {
                this.durumBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<long> EsTCKimlikNo
        {
            get
            {
                return this.esTCKimlikNoField;
            }
            set
            {
                this.esTCKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public TCKisiKayitYeriBilgisi KayitYeriBilgisi
        {
            get
            {
                return this.kayitYeriBilgisiField;
            }
            set
            {
                this.kayitYeriBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<long> TCKimlikNo
        {
            get
            {
                return this.tCKimlikNoField;
            }
            set
            {
                this.tCKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public TCKisiTemelBilgisi TemelBilgisi
        {
            get
            {
                return this.temelBilgisiField;
            }
            set
            {
                this.temelBilgisiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class TCGeciciKimlikBilgisi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string adField;
        
        private string anneAdField;
        
        private string babaAdField;
        
        private string belgeNoField;
        
        private Parametre cinsiyetField;
        
        private TarihBilgisi dogumTarihField;
        
        private TarihBilgisi duzenlenmeTarihField;
        
        private Parametre duzenleyenIlceField;
        
        private Parametre hataBilgisiField;
        
        private string oncekiSoyadField;
        
        private TarihBilgisi sonGecerlilikTarihField;
        
        private string soyadField;
        
        private System.Nullable<long> tCKimlikNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ad
        {
            get
            {
                return this.adField;
            }
            set
            {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AnneAd
        {
            get
            {
                return this.anneAdField;
            }
            set
            {
                this.anneAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BabaAd
        {
            get
            {
                return this.babaAdField;
            }
            set
            {
                this.babaAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BelgeNo
        {
            get
            {
                return this.belgeNoField;
            }
            set
            {
                this.belgeNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Parametre Cinsiyet
        {
            get
            {
                return this.cinsiyetField;
            }
            set
            {
                this.cinsiyetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public TarihBilgisi DogumTarih
        {
            get
            {
                return this.dogumTarihField;
            }
            set
            {
                this.dogumTarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public TarihBilgisi DuzenlenmeTarih
        {
            get
            {
                return this.duzenlenmeTarihField;
            }
            set
            {
                this.duzenlenmeTarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Parametre DuzenleyenIlce
        {
            get
            {
                return this.duzenleyenIlceField;
            }
            set
            {
                this.duzenleyenIlceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string OncekiSoyad
        {
            get
            {
                return this.oncekiSoyadField;
            }
            set
            {
                this.oncekiSoyadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public TarihBilgisi SonGecerlilikTarih
        {
            get
            {
                return this.sonGecerlilikTarihField;
            }
            set
            {
                this.sonGecerlilikTarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Soyad
        {
            get
            {
                return this.soyadField;
            }
            set
            {
                this.soyadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<long> TCKimlikNo
        {
            get
            {
                return this.tCKimlikNoField;
            }
            set
            {
                this.tCKimlikNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class TCVatandasiKisiKutukleri
    {
        
        private ExtensionDataObject extensionDataField;
        
        private TCGeciciKimlikBilgisi geciciKimlikBilgisiField;
        
        private Parametre hataBilgisiField;
        
        private TCKisiBilgisi kisiBilgisiField;
        
        private TCCuzdanBilgisi nufusCuzdaniBilgisiField;
        
        private TCKK tCKKBilgisiField;
        
        private TCKKFotoBilgisi tCKKFotografBilgisiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TCGeciciKimlikBilgisi GeciciKimlikBilgisi
        {
            get
            {
                return this.geciciKimlikBilgisiField;
            }
            set
            {
                this.geciciKimlikBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TCKisiBilgisi KisiBilgisi
        {
            get
            {
                return this.kisiBilgisiField;
            }
            set
            {
                this.kisiBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TCCuzdanBilgisi NufusCuzdaniBilgisi
        {
            get
            {
                return this.nufusCuzdaniBilgisiField;
            }
            set
            {
                this.nufusCuzdaniBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public TCKK TCKKBilgisi
        {
            get
            {
                return this.tCKKBilgisiField;
            }
            set
            {
                this.tCKKBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public TCKKFotoBilgisi TCKKFotografBilgisi
        {
            get
            {
                return this.tCKKFotografBilgisiField;
            }
            set
            {
                this.tCKKFotografBilgisiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class MaviKartBilgi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string adField;
        
        private string anneAdField;
        
        private string babaAdField;
        
        private System.Nullable<int> birimField;
        
        private Parametre cinsiyetField;
        
        private TarihBilgisi dogumTarihField;
        
        private string dogumYerField;
        
        private System.Nullable<int> dogumYerKodField;
        
        private Parametre hataBilgisiField;
        
        private System.Nullable<long> kartKayitNoField;
        
        private System.Nullable<long> kimlikNoField;
        
        private Parametre medeniHalField;
        
        private System.Nullable<int> noField;
        
        private string oncekiSoyadField;
        
        private string seriField;
        
        private string soyadField;
        
        private Parametre uyrukField;
        
        private Parametre verilisNedenField;
        
        private TarihBilgisi verilmeTarihField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ad
        {
            get
            {
                return this.adField;
            }
            set
            {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AnneAd
        {
            get
            {
                return this.anneAdField;
            }
            set
            {
                this.anneAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BabaAd
        {
            get
            {
                return this.babaAdField;
            }
            set
            {
                this.babaAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> Birim
        {
            get
            {
                return this.birimField;
            }
            set
            {
                this.birimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Parametre Cinsiyet
        {
            get
            {
                return this.cinsiyetField;
            }
            set
            {
                this.cinsiyetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public TarihBilgisi DogumTarih
        {
            get
            {
                return this.dogumTarihField;
            }
            set
            {
                this.dogumTarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DogumYer
        {
            get
            {
                return this.dogumYerField;
            }
            set
            {
                this.dogumYerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> DogumYerKod
        {
            get
            {
                return this.dogumYerKodField;
            }
            set
            {
                this.dogumYerKodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<long> KartKayitNo
        {
            get
            {
                return this.kartKayitNoField;
            }
            set
            {
                this.kartKayitNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<long> KimlikNo
        {
            get
            {
                return this.kimlikNoField;
            }
            set
            {
                this.kimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public Parametre MedeniHal
        {
            get
            {
                return this.medeniHalField;
            }
            set
            {
                this.medeniHalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<int> No
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string OncekiSoyad
        {
            get
            {
                return this.oncekiSoyadField;
            }
            set
            {
                this.oncekiSoyadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Seri
        {
            get
            {
                return this.seriField;
            }
            set
            {
                this.seriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Soyad
        {
            get
            {
                return this.soyadField;
            }
            set
            {
                this.soyadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public Parametre Uyruk
        {
            get
            {
                return this.uyrukField;
            }
            set
            {
                this.uyrukField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public Parametre VerilisNeden
        {
            get
            {
                return this.verilisNedenField;
            }
            set
            {
                this.verilisNedenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public TarihBilgisi VerilmeTarih
        {
            get
            {
                return this.verilmeTarihField;
            }
            set
            {
                this.verilmeTarihField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class MaviKartKisiTemelBilgisi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private string adField;
        
        private string anneAdField;
        
        private string babaAdField;
        
        private Parametre cinsiyetField;
        
        private TarihBilgisi dogumTarihField;
        
        private string dogumYerField;
        
        private string soyadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ad
        {
            get
            {
                return this.adField;
            }
            set
            {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AnneAd
        {
            get
            {
                return this.anneAdField;
            }
            set
            {
                this.anneAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BabaAd
        {
            get
            {
                return this.babaAdField;
            }
            set
            {
                this.babaAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Parametre Cinsiyet
        {
            get
            {
                return this.cinsiyetField;
            }
            set
            {
                this.cinsiyetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public TarihBilgisi DogumTarih
        {
            get
            {
                return this.dogumTarihField;
            }
            set
            {
                this.dogumTarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DogumYer
        {
            get
            {
                return this.dogumYerField;
            }
            set
            {
                this.dogumYerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Soyad
        {
            get
            {
                return this.soyadField;
            }
            set
            {
                this.soyadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class MaviKartKisiDurumBilgisi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private Parametre durumField;
        
        private Parametre medeniHalField;
        
        private TarihBilgisi olumTarihField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Parametre Durum
        {
            get
            {
                return this.durumField;
            }
            set
            {
                this.durumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Parametre MedeniHal
        {
            get
            {
                return this.medeniHalField;
            }
            set
            {
                this.medeniHalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TarihBilgisi OlumTarih
        {
            get
            {
                return this.olumTarihField;
            }
            set
            {
                this.olumTarihField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class MaviKartKisiBilgisi
    {
        
        private ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> anneTCKimlikNoField;
        
        private System.Nullable<long> babaTCKimlikNoField;
        
        private System.Nullable<int> dogumYerKodField;
        
        private MaviKartKisiDurumBilgisi durumBilgisiField;
        
        private System.Nullable<long> esTCKimlikNoField;
        
        private System.Nullable<long> gercekKisiKimlikNoField;
        
        private Parametre hataBilgisiField;
        
        private System.Nullable<long> kazanilanTCKimlikNoField;
        
        private System.Nullable<long> kimlikNoField;
        
        private MaviKartKisiTemelBilgisi temelBilgisiField;
        
        private Parametre ulkeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<long> AnneTCKimlikNo
        {
            get
            {
                return this.anneTCKimlikNoField;
            }
            set
            {
                this.anneTCKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> BabaTCKimlikNo
        {
            get
            {
                return this.babaTCKimlikNoField;
            }
            set
            {
                this.babaTCKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> DogumYerKod
        {
            get
            {
                return this.dogumYerKodField;
            }
            set
            {
                this.dogumYerKodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public MaviKartKisiDurumBilgisi DurumBilgisi
        {
            get
            {
                return this.durumBilgisiField;
            }
            set
            {
                this.durumBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<long> EsTCKimlikNo
        {
            get
            {
                return this.esTCKimlikNoField;
            }
            set
            {
                this.esTCKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<long> GercekKisiKimlikNo
        {
            get
            {
                return this.gercekKisiKimlikNoField;
            }
            set
            {
                this.gercekKisiKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<long> KazanilanTCKimlikNo
        {
            get
            {
                return this.kazanilanTCKimlikNoField;
            }
            set
            {
                this.kazanilanTCKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<long> KimlikNo
        {
            get
            {
                return this.kimlikNoField;
            }
            set
            {
                this.kimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public MaviKartKisiTemelBilgisi TemelBilgisi
        {
            get
            {
                return this.temelBilgisiField;
            }
            set
            {
                this.temelBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public Parametre Ulke
        {
            get
            {
                return this.ulkeField;
            }
            set
            {
                this.ulkeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class MaviKartKisiKutukleri
    {
        
        private ExtensionDataObject extensionDataField;
        
        private Parametre hataBilgisiField;
        
        private MaviKartKisiBilgisi kisiBilgisiField;
        
        private MaviKartBilgi maviKartBilgisiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MaviKartKisiBilgisi KisiBilgisi
        {
            get
            {
                return this.kisiBilgisiField;
            }
            set
            {
                this.kisiBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public MaviKartBilgi MaviKartBilgisi
        {
            get
            {
                return this.maviKartBilgisiField;
            }
            set
            {
                this.maviKartBilgisiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class BilesikKutukBilgileri
    {
        
        private ExtensionDataObject extensionDataField;
        
        private Parametre hataBilgisiField;
        
        private System.Nullable<long> kimlikNoField;
        
        private MaviKartKisiKutukleri maviKartliKisiKutukleriField;
        
        private TCVatandasiKisiKutukleri tCVatandasiKisiKutukleriField;
        
        private YabanciKisiKutukleri yabanciKisiKutukleriField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> KimlikNo
        {
            get
            {
                return this.kimlikNoField;
            }
            set
            {
                this.kimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public MaviKartKisiKutukleri MaviKartliKisiKutukleri
        {
            get
            {
                return this.maviKartliKisiKutukleriField;
            }
            set
            {
                this.maviKartliKisiKutukleriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TCVatandasiKisiKutukleri TCVatandasiKisiKutukleri
        {
            get
            {
                return this.tCVatandasiKisiKutukleriField;
            }
            set
            {
                this.tCVatandasiKisiKutukleriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public YabanciKisiKutukleri YabanciKisiKutukleri
        {
            get
            {
                return this.yabanciKisiKutukleriField;
            }
            set
            {
                this.yabanciKisiKutukleriField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class BilesikKutukBilgileriSonucu
    {
        
        private ExtensionDataObject extensionDataField;
        
        private Parametre hataBilgisiField;
        
        private BilesikKutukBilgileri[] sorguSonucuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Parametre HataBilgisi
        {
            get
            {
                return this.hataBilgisiField;
            }
            set
            {
                this.hataBilgisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public BilesikKutukBilgileri[] SorguSonucu
        {
            get
            {
                return this.sorguSonucuField;
            }
            set
            {
                this.sorguSonucuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
    public partial class BilesikKutukSorgulaKimlikNoSorguKriteri
    {
        
        private ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> kimlikNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<long> KimlikNo
        {
            get
            {
                return this.kimlikNoField;
            }
            set
            {
                this.kimlikNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BilesikKutukSorgulaKimlikNoServis", WrapperNamespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/", IsWrapped=true)]
    public partial class BilesikKutukSorgulaKimlikNoServisRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/")]
        public BilesikKutukServis.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/", Order=0)]
        public BilesikKutukServis.BilesikKutukSorgulaKimlikNoSorguKriteri[] kriterList;
        
        public BilesikKutukSorgulaKimlikNoServisRequest()
        {
        }
        
        public BilesikKutukSorgulaKimlikNoServisRequest(BilesikKutukServis.AuthHeader AuthHeader, BilesikKutukServis.BilesikKutukSorgulaKimlikNoSorguKriteri[] kriterList)
        {
            this.AuthHeader = AuthHeader;
            this.kriterList = kriterList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BilesikKutukSorgulaKimlikNoServisResponse", WrapperNamespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/", IsWrapped=true)]
    public partial class BilesikKutukSorgulaKimlikNoServisResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aile.gov.tr/WebServices/Mernis/BilesikKutukSorgulaKimlikNoService/", Order=0)]
        public BilesikKutukServis.BilesikKutukBilgileriSonucu BilesikKutukSorgulaKimlikNoServisResult;
        
        public BilesikKutukSorgulaKimlikNoServisResponse()
        {
        }
        
        public BilesikKutukSorgulaKimlikNoServisResponse(BilesikKutukServis.BilesikKutukBilgileriSonucu BilesikKutukSorgulaKimlikNoServisResult)
        {
            this.BilesikKutukSorgulaKimlikNoServisResult = BilesikKutukSorgulaKimlikNoServisResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface BilesikKutukSorgulaKimlikNoServiceSoapChannel : BilesikKutukServis.BilesikKutukSorgulaKimlikNoServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class BilesikKutukSorgulaKimlikNoServiceSoapClient : System.ServiceModel.ClientBase<BilesikKutukServis.BilesikKutukSorgulaKimlikNoServiceSoap>, BilesikKutukServis.BilesikKutukSorgulaKimlikNoServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BilesikKutukSorgulaKimlikNoServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(BilesikKutukSorgulaKimlikNoServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), BilesikKutukSorgulaKimlikNoServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BilesikKutukSorgulaKimlikNoServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BilesikKutukSorgulaKimlikNoServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BilesikKutukSorgulaKimlikNoServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BilesikKutukSorgulaKimlikNoServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BilesikKutukSorgulaKimlikNoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BilesikKutukServis.BilesikKutukSorgulaKimlikNoServisResponse> BilesikKutukServis.BilesikKutukSorgulaKimlikNoServiceSoap.BilesikKutukSorgulaKimlikNoServisAsync(BilesikKutukServis.BilesikKutukSorgulaKimlikNoServisRequest request)
        {
            return base.Channel.BilesikKutukSorgulaKimlikNoServisAsync(request);
        }
        
        public System.Threading.Tasks.Task<BilesikKutukServis.BilesikKutukSorgulaKimlikNoServisResponse> BilesikKutukSorgulaKimlikNoServisAsync(BilesikKutukServis.AuthHeader AuthHeader, BilesikKutukServis.BilesikKutukSorgulaKimlikNoSorguKriteri[] kriterList)
        {
            BilesikKutukServis.BilesikKutukSorgulaKimlikNoServisRequest inValue = new BilesikKutukServis.BilesikKutukSorgulaKimlikNoServisRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.kriterList = kriterList;
            return ((BilesikKutukServis.BilesikKutukSorgulaKimlikNoServiceSoap)(this)).BilesikKutukSorgulaKimlikNoServisAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<BilesikKutukServis.BilesikKutukBilgileriSonucu> BilesikKutukSorgulaKimlikNoServisMpAsync(BilesikKutukServis.BilesikKutukSorgulaKimlikNoSorguKriteri[] kriterList, string username, string password, string sessionID, string sorgulayanKullanici)
        {
            return base.Channel.BilesikKutukSorgulaKimlikNoServisMpAsync(kriterList, username, password, sessionID, sorgulayanKullanici);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BilesikKutukSorgulaKimlikNoServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BilesikKutukSorgulaKimlikNoServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BilesikKutukSorgulaKimlikNoServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://wsint130.ailevecalisma.gov.tr/KimlikNoileBirlesikKutukSorgula/BilesikKutuk" +
                        "SorgulaKimlikNoService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.BilesikKutukSorgulaKimlikNoServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://wsint130.ailevecalisma.gov.tr/KimlikNoileBirlesikKutukSorgula/BilesikKutuk" +
                        "SorgulaKimlikNoService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BilesikKutukSorgulaKimlikNoServiceSoap,
            
            BilesikKutukSorgulaKimlikNoServiceSoap12,
        }
    }
}
